/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_spk_saw;

import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ferdy
 */
public class Form_Kriteria extends javax.swing.JFrame {
    int nis = 0;
    int kd_kriteria = 0;
    int kdpd, kdsikap, kdekskul, kdnilai;
    double k1d, k2d, k3d, k4d, k5d;
    double rataakademik, ratapd, ratasikap, rataekskul;
    String kelas = "";
    String semester = "";
    String tahunajaran = "";
    String kategori1 = "";
    String kategori2 = "";
    DefaultTableModel tmodel1, tmodel2, tmodel3, tmodel4;
    
    
    
    private void getKriteriaSiswa() {
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT nk.kd_kriteria, nk.nis_siswa, nk.nama, npd.Ratarata_Pd, ns.Ratarata_Sikap, ne.Ratarata_Ekskul, nk.absensi, "
                    + "dn.Nilai_Ratarata, nk.kelas, nk.semester, nk.tahun_ajaran from (tb_nilaikriteria nk left JOIN tb_nilaipd npd on nk.kd_nilaipd = npd.kd_nilaipd)"
                    + " LEFT JOIN tb_nilaisikap ns on nk.kd_nilaisikap = ns.kd_nilaisikap LEFT JOIN tb_nilaiekskul ne on nk.kd_nilaiekskul = ne.kd_nilaiekskul LEFT JOIN "
                    + "tb_datanilai dn on nk.kd_nilai = dn.kd_nilai;");
            nilaikriteriaTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
    }
    
    
    private void tampilkan(){
        if(kelas.equals("") || semester.equals("") || tahunajaran.equals("")){
            tampilkan1Btn.setEnabled(false);
        } else {
            tampilkan1Btn.setEnabled(true);
        }
    }
    
    

    /**
     * Creates new form Form_Kriteria
     */
    public Form_Kriteria() {
        initComponents();
        getKriteriaSiswa();
        nisTxt.setEditable(false);
        namaTxt.setEditable(false);
        kelasTxt.setEditable(false);
        semesterTxt.setEditable(false);
        absensiTxt.setEditable(false);
        tahunajaranTxt.setEditable(false);
        nilaiakademikTxt.setEditable(false);
        nilaipdTxt.setEditable(false);
        nilaisikapTxt.setEditable(false);
        nilaiekskulTxt.setEditable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nisTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namaTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kelasTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        semesterTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tahunajaranTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nilaiakademikTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nilaipdTxt = new javax.swing.JTextField();
        nilaisikapTxt = new javax.swing.JTextField();
        nilaiekskulTxt = new javax.swing.JTextField();
        simpanBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        bersihkanBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        absensiTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kdnilaikriteriaTxt = new javax.swing.JTextField();
        absensiCmb = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        akademikPnl = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        siswaTbl2 = new javax.swing.JTable();
        pdPnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        nilaipdTbl = new javax.swing.JTable();
        sikapPnl = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        nilaisikapTbl = new javax.swing.JTable();
        ekskulPnl = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        nilaiekskulTbl = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        nilaikriteriaTbl = new javax.swing.JTable();
        kelasCmb = new javax.swing.JComboBox<>();
        semesterCmb = new javax.swing.JComboBox<>();
        tahunajaranCmb = new javax.swing.JComboBox<>();
        cari1Txt = new javax.swing.JTextField();
        tampilkan1Btn = new javax.swing.JButton();
        refresh1Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Kriteria Siswa");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/computer.png")).getImage());
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nilai Kriteria Siswa"));

        jLabel1.setText("NIS");

        jLabel2.setText("Nama");

        jLabel3.setText("Kelas");

        jLabel4.setText("Semester");

        jLabel5.setText("Tahun Ajaran");

        jLabel8.setText("Nilai PD");

        jLabel9.setText("Nilai Sikap");

        jLabel10.setText("Absensi");

        jLabel13.setText("Nilai Akademik");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText(" - Kriteria -");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("- Nilai -");

        nilaipdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaipdTxtActionPerformed(evt);
            }
        });

        simpanBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        simpanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Upload.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        hapusBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hapusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        bersihkanBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bersihkanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clear.png"))); // NOI18N
        bersihkanBtn.setText("Clear");
        bersihkanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanBtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Help.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Nilai Ekskul");

        jLabel6.setText("Kode Nilai Kriteria");

        absensiCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Ketidakhadiran-", "0-2 Kali Tidak Hadir", "3-5 Kali Tidak Hadir", "6-9 Kali Tidak Hadir", "10-13 Kali Tidak Hadir", ">13 Kali Tidak Hadir" }));
        absensiCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absensiCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tahunajaranTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(semesterTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kelasTxt, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(simpanBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapusBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(89, 89, 89))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(78, 78, 78))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(kdnilaikriteriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nilaisikapTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nilaipdTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nilaiakademikTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(absensiCmb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nilaiekskulTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bersihkanBtn)
                            .addComponent(absensiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kelasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(semesterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tahunajaranTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kdnilaikriteriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nilaipdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nilaisikapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nilaiekskulTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nilaiakademikTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(absensiCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(absensiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanBtn)
                    .addComponent(updateBtn)
                    .addComponent(hapusBtn)
                    .addComponent(bersihkanBtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        siswaTbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd Nilai", "NIS", "Nama", "Rata-rata Nilai", "Kelas", "Semester", "Tahun Ajaran"
            }
        ));
        siswaTbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siswaTbl2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(siswaTbl2);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        jScrollPane12.setViewportView(jPanel9);

        javax.swing.GroupLayout akademikPnlLayout = new javax.swing.GroupLayout(akademikPnl);
        akademikPnl.setLayout(akademikPnlLayout);
        akademikPnlLayout.setHorizontalGroup(
            akademikPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12)
        );
        akademikPnlLayout.setVerticalGroup(
            akademikPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12)
        );

        jTabbedPane3.addTab("Data Nilai Akademik", akademikPnl);

        nilaipdTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd Nilai Pd", "Nis", "Nama", "Muhadroh", "Tahfizh", "Rata-rata", "Kelas", "Semester", "Tahun Ajaran"
            }
        ));
        nilaipdTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nilaipdTblMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(nilaipdTbl);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel10);

        javax.swing.GroupLayout pdPnlLayout = new javax.swing.GroupLayout(pdPnl);
        pdPnl.setLayout(pdPnlLayout);
        pdPnlLayout.setHorizontalGroup(
            pdPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        pdPnlLayout.setVerticalGroup(
            pdPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Data Nilai PD", pdPnl);

        nilaisikapTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd Nilai Sikap", "NIS", "Nama", "Kelakuan", "Kerajinan", "Kebersihan", "Rata-rata", "Kelas", "Semester", "Tahun Ajaran"
            }
        ));
        nilaisikapTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nilaisikapTblMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(nilaisikapTbl);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel5);

        javax.swing.GroupLayout sikapPnlLayout = new javax.swing.GroupLayout(sikapPnl);
        sikapPnl.setLayout(sikapPnlLayout);
        sikapPnlLayout.setHorizontalGroup(
            sikapPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        sikapPnlLayout.setVerticalGroup(
            sikapPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Data Nilai Sikap", sikapPnl);

        nilaiekskulTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd Nilai Ekskul", "NIS", "Nama", "Pramuka", "Silat", "Paskibra", "Rata-rata", "Kelas", "Semester"
            }
        ));
        nilaiekskulTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nilaiekskulTblMouseClicked(evt);
            }
        });
        jScrollPane13.setViewportView(nilaiekskulTbl);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        jScrollPane11.setViewportView(jPanel13);

        javax.swing.GroupLayout ekskulPnlLayout = new javax.swing.GroupLayout(ekskulPnl);
        ekskulPnl.setLayout(ekskulPnlLayout);
        ekskulPnlLayout.setHorizontalGroup(
            ekskulPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        ekskulPnlLayout.setVerticalGroup(
            ekskulPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Data Nilai Ekskul", ekskulPnl);

        nilaikriteriaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd_Kriteria", "NIS", "Nama", "Nilai PD", "Nilai Sikap", "Nilai Ekskul", "Absensi", "Akademik", "Kelas", "Semester", "Tahun Ajaran"
            }
        ));
        nilaikriteriaTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nilaikriteriaTblMouseClicked(evt);
            }
        });
        jScrollPane14.setViewportView(nilaikriteriaTbl);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 1065, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(jPanel14);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );

        jTabbedPane3.addTab("Data Nilai Kriteria Siswa", jPanel8);

        kelasCmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kelasCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Kelas-", "VII-A", "VII-B", "VIII-A", "VIII-B", "IX-A", "IX-B" }));
        kelasCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasCmbActionPerformed(evt);
            }
        });

        semesterCmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        semesterCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Semester-", "Ganjil", "Genap" }));
        semesterCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterCmbActionPerformed(evt);
            }
        });

        tahunajaranCmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tahunajaranCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Tahun Ajaran-", "2018/2019", "2019/2020", "2020/2021", "2021/2022", "2022/2023", "2023/2024", "Input Manual" }));
        tahunajaranCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunajaranCmbActionPerformed(evt);
            }
        });

        cari1Txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tampilkan1Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tampilkan1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Show.png"))); // NOI18N
        tampilkan1Btn.setText("Tampilkan");
        tampilkan1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkan1BtnActionPerformed(evt);
            }
        });

        refresh1Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refresh1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        refresh1Btn.setText("Refresh");
        refresh1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kelasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(semesterCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tahunajaranCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cari1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tampilkan1Btn)
                .addGap(18, 18, 18)
                .addComponent(refresh1Btn))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semesterCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahunajaranCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tampilkan1Btn)
                    .addComponent(refresh1Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3))
        );

        jTabbedPane3.getAccessibleContext().setAccessibleName("Data Siswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nilaipdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaipdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaipdTxtActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        String nisnya = null;
        String namanya = null;
        String kelasnya = null;
        String semesternya = null;
        if (nisTxt.getText().equals("") || namaTxt.getText().equals("") || kelasTxt.getText().equals("") || semesterTxt.getText().equals("") || tahunajaranTxt.getText().equals("")
                || nilaipdTxt.getText().equals("") || nilaisikapTxt.getText().equals("") || nilaiekskulTxt.getText().equals("")
                || absensiTxt.getText().equals("") || nilaiakademikTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu dengan memilih data ditabel!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            k1d = Double.parseDouble(nilaipdTxt.getText());
            k2d = Double.parseDouble(nilaisikapTxt.getText());
            k3d = Double.parseDouble(nilaiekskulTxt.getText());
            k4d = Double.parseDouble(absensiTxt.getText());
            k5d = Double.parseDouble(nilaiakademikTxt.getText());
        try {
           java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
           java.sql.Statement stm = conn.createStatement();
           java.sql.ResultSet sqll = stm.executeQuery("SELECT Nis_Siswa, Nama, Kelas, Semester FROM tb_nilaikriteria WHERE Nis_Siswa='"+nisTxt.getText()+"' AND Kelas='"+kelasTxt.getText()+"' AND Semester='"+semesterTxt.getText()+"'");        
           if (sqll.next()) {
               nis = sqll.getInt("Nis_Siswa");
               nisnya = Integer.toString(nis);
               namanya = sqll.getString("Nama");
               kelasnya = sqll.getString("Kelas");
               semesternya = sqll.getString("Semester");
           } else {}
           if (nisTxt.getText().equals(nisnya) && kelasTxt.getText().equals(kelasnya) && semesterTxt.getText().equals(semesternya)){
           JOptionPane.showMessageDialog(null, "Nilai kriteria "+namaTxt.getText()+" kelas "+kelasTxt.getText()+" pada semester "+semesterTxt.getText()+" sudah ada!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);    
           } else {         
                String sql = "INSERT INTO tb_nilaikriteria VALUES('"+kdnilaikriteriaTxt.getText()+"','"+nisTxt.getText()+"','"+namaTxt.getText()+"','"+kdpd+"','"+kdsikap+"','"+kdekskul+"','"+k4d+"','"+kdnilai+"',"
                        + "'"+kelasTxt.getText()+"','"+semesterTxt.getText()+"','"+tahunajaranTxt.getText()+"')";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                String sqlll = "INSERT INTO tb_altkriteria VALUES('"+kdnilaikriteriaTxt.getText()+"','"+nisTxt.getText()+"','"+namaTxt.getText()+"','"+k1d+"','"+k2d+"','"+k3d+"','"+k4d+"','"+k5d+"',"
                        + "'"+kelasTxt.getText()+"','"+semesterTxt.getText()+"','"+tahunajaranTxt.getText()+"')";
                java.sql.PreparedStatement psy = conn.prepareStatement(sqlll);
                psy.execute();
                JOptionPane.showMessageDialog(null, "Nilai kriteria siswa berhasil disimpan!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
           }
        } catch (SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Nilai kriteria siswa gagal disimpan!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        kd_kriteria = 0;
        nisTxt.setText("");
        namaTxt.setText("");
        kelasTxt.setText("");
        kdnilaikriteriaTxt.setText("");
        semesterTxt.setText("");
        tahunajaranTxt.setText("");
        absensiTxt.setText("");
        nilaiakademikTxt.setText("");
        nilaipdTxt.setText("");
        nilaisikapTxt.setText("");
        nilaiekskulTxt.setText("");
        absensiCmb.setSelectedIndex(0);
        getKriteriaSiswa();
        }
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if (kd_kriteria == 0){
            JOptionPane.showMessageDialog(null, "Pilih nilai kriteria siswa yang ingin diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
        if (nisTxt.getText().equals("") || namaTxt.getText().equals("") || kelasTxt.getText().equals("") || semesterTxt.getText().equals("") || tahunajaranTxt.getText().equals("")
                || nilaipdTxt.getText().equals("") || nilaisikapTxt.getText().equals("") || nilaiekskulTxt.getText().equals("") ||
                absensiTxt.getText().equals("") || nilaiakademikTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            k1d = Double.parseDouble(nilaipdTxt.getText());
            k2d = Double.parseDouble(nilaisikapTxt.getText());
            k3d = Double.parseDouble(nilaiekskulTxt.getText());
            k4d = Double.parseDouble(absensiTxt.getText());
            k5d = Double.parseDouble(nilaiakademikTxt.getText());
        try {
                java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                String sql = "UPDATE tb_nilaikriteria SET Nis_Siswa='"+nisTxt.getText()+"', Nama='"+namaTxt.getText()+"', Kd_NilaiPd='"+kdpd+"', Kd_NilaiSikap='"+kdsikap+"', Kd_NilaiEkskul='"+kdekskul+"', Absensi='"+k4d+"', Kd_Nilai='"+kdnilai+"',"
                        + " Kelas='"+kelasTxt.getText()+"', Semester='"+semesterTxt.getText()+"', Tahun_Ajaran='"+tahunajaranTxt.getText()+"' WHERE Kd_Kriteria='"+kd_kriteria+"'";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                String sqll = "UPDATE tb_altkriteria SET Nis_Siswa='"+nisTxt.getText()+"', Nama='"+namaTxt.getText()+"', Nilai_Pd='"+k1d+"', Nilai_Sikap='"+k2d+"', Nilai_Ekskul='"+k3d+"', Absensi='"+k4d+"', akademik='"+k5d+"',"
                        + " Kelas='"+kelasTxt.getText()+"', Semester='"+semesterTxt.getText()+"', Tahun_Ajaran='"+tahunajaranTxt.getText()+"' WHERE Kd_AltKriteria='"+kd_kriteria+"'";
                java.sql.PreparedStatement psy = conn.prepareStatement(sqll);
                psy.execute();
                JOptionPane.showMessageDialog(null, "Nilai kriteria siswa berhasil diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Nilai kriteria siswa gagal diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        }
        getKriteriaSiswa();
        kdnilaikriteriaTxt.setEnabled(true);
        kd_kriteria = 0;
        nisTxt.setText("");
        namaTxt.setText("");
        kelasTxt.setText("");
        kdnilaikriteriaTxt.setText("");
        semesterTxt.setText("");
        tahunajaranTxt.setText("");
        absensiTxt.setText("");
        nilaiakademikTxt.setText("");
        nilaipdTxt.setText("");
        nilaisikapTxt.setText("");
        nilaiekskulTxt.setText("");
        absensiCmb.setSelectedIndex(0);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        // TODO add your handling code here:
        if (kd_kriteria == 0){
            JOptionPane.showMessageDialog(null, "Pilih nilai kriteria siswa yang ingin dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            Object[] options = {"Iya", "Tidak"};
            int van = JOptionPane.showOptionDialog(this, "Anda yakin ingin menghapus data nilai kriteria "+namaTxt.getText()+"?",
            "Konfirmasi", JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            if(van== 0){
                try {
                    java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                    String sql = "DELETE FROM tb_nilaikriteria WHERE Kd_Kriteria='"+kd_kriteria+"'";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    String sqll = "DELETE FROM tb_altkriteria WHERE Kd_AltKriteria='"+kd_kriteria+"'";
                    java.sql.PreparedStatement psy = conn.prepareStatement(sqll);
                    psy.execute();
                    JOptionPane.showMessageDialog(null, "Nilai kriteria siswa berhasil dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException | HeadlessException e) {
                    JOptionPane.showMessageDialog(null, "Nilai kriteria siswa gagal dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                }
                getKriteriaSiswa();}
            else if(van== 1){
            }
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void bersihkanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanBtnActionPerformed
        // TODO add your handling code here:
        kdnilaikriteriaTxt.setEnabled(true);
        kd_kriteria = 0;
        nisTxt.setText("");
        namaTxt.setText("");
        kelasTxt.setText("");
        kdnilaikriteriaTxt.setText("");
        semesterTxt.setText("");
        tahunajaranTxt.setText("");
        absensiTxt.setText("");
        nilaiakademikTxt.setText("");
        nilaipdTxt.setText("");
        nilaisikapTxt.setText("");
        nilaiekskulTxt.setText("");
        absensiCmb.setSelectedIndex(0);
    }//GEN-LAST:event_bersihkanBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Lihat petunjuk pada tampilan utama aplikasi ini.","Petunjuk",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tampilkan1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkan1BtnActionPerformed
        // TODO add your handling code here:
        if(tahunajaranCmb.getSelectedIndex()==7){
            tahunajaran=cari1Txt.getText();}
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT Kd_Nilai, Nis_Siswa, Nama, Nilai_Ratarata, Kelas, Semester, Tahun_Ajaran FROM tb_datanilai WHERE Kelas='"+kelas+"' AND Semester='"+semester+"' AND Tahun_Ajaran='"+tahunajaran+"'");

            siswaTbl2.setModel(DbUtils.resultSetToTableModel(sql));


        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_tampilkan1BtnActionPerformed

    private void refresh1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1BtnActionPerformed
        // TODO add your handling code here:
        getKriteriaSiswa();
        cari1Txt.setText("");
        kelasCmb.setSelectedIndex(0);
        semesterCmb.setSelectedIndex(0);
        tahunajaranCmb.setSelectedIndex(0);
        tmodel4 = (DefaultTableModel)nilaiekskulTbl.getModel();
        tmodel3 = (DefaultTableModel)nilaisikapTbl.getModel();
        tmodel2 = (DefaultTableModel)nilaipdTbl.getModel();
        tmodel1 = (DefaultTableModel)siswaTbl2.getModel();
        tmodel4.setRowCount(0);
        tmodel1.setRowCount(0);
        tmodel2.setRowCount(0);
        tmodel3.setRowCount(0);
    }//GEN-LAST:event_refresh1BtnActionPerformed

    private void kelasCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasCmbActionPerformed
        // TODO add your handling code here:
        if (kelasCmb.getSelectedIndex()==0){
            kelas="";}
        else if(kelasCmb.getSelectedIndex()==1){
            kelas="VII-A";}
        else if(kelasCmb.getSelectedIndex()==2){
            kelas="VII-B";}
        else if(kelasCmb.getSelectedIndex()==3){
            kelas="VIII-A";}
        else if(kelasCmb.getSelectedIndex()==4){
            kelas="VIII-B";}
        else if(kelasCmb.getSelectedIndex()==5){
            kelas="IX-A";}
        else if(kelasCmb.getSelectedIndex()==6){
            kelas="IX-B";}
        tampilkan();
    }//GEN-LAST:event_kelasCmbActionPerformed

    private void semesterCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterCmbActionPerformed
        // TODO add your handling code here:
        if (semesterCmb.getSelectedIndex()==0){
            semester="";}
        else if(semesterCmb.getSelectedIndex()==1){
            semester="Ganjil";}
        else if(semesterCmb.getSelectedIndex()==2){
            semester="Genap";}
        tampilkan();
    }//GEN-LAST:event_semesterCmbActionPerformed

    private void tahunajaranCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunajaranCmbActionPerformed
        // TODO add your handling code here:
        if (tahunajaranCmb.getSelectedIndex()==0){
            cari1Txt.setEnabled(false);
            cari1Txt.setText("");
            tahunajaran="";}
        else if(tahunajaranCmb.getSelectedIndex()==1){
            cari1Txt.setEnabled(false);
            cari1Txt.setText("");
            tahunajaran="2018/2019";}
        else if(tahunajaranCmb.getSelectedIndex()==2){
            cari1Txt.setEnabled(false);
            cari1Txt.setText("");
            tahunajaran="2019/2020";}
        else if(tahunajaranCmb.getSelectedIndex()==3){
            cari1Txt.setEnabled(false);
            cari1Txt.setText("");
            tahunajaran="2020/2021";}
        else if(tahunajaranCmb.getSelectedIndex()==4){
            cari1Txt.setEnabled(false);
            cari1Txt.setText("");
            tahunajaran="2021/2022";}
        else if(tahunajaranCmb.getSelectedIndex()==5){
            cari1Txt.setEnabled(false);
            cari1Txt.setText("");
            tahunajaran="2022/2023";}
        else if(tahunajaranCmb.getSelectedIndex()==6){
            cari1Txt.setEnabled(false);
            cari1Txt.setText("");
            tahunajaran="2023/2024";}
        else if(tahunajaranCmb.getSelectedIndex()==7){
            cari1Txt.setEnabled(true);
            tahunajaran=cari1Txt.getText();}
        tampilkan();
    }//GEN-LAST:event_tahunajaranCmbActionPerformed

    private void nilaipdTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nilaipdTblMouseClicked
        // TODO add your handling code here:
        int niss = 0;
        String nisnya = null;
        try {
            int row = nilaipdTbl.getSelectedRow();
            String kliktabel=(nilaipdTbl.getModel().getValueAt(row,0).toString());
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.Statement stmm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaipd WHERE Kd_NilaiPd='"+kliktabel+"'");
            java.sql.ResultSet sqll = stmm.executeQuery("SELECT * FROM tb_nilaipd WHERE Kd_NilaiPd='"+kliktabel+"'");
            if (sqll.next()) {
                    niss = sqll.getInt("Nis_siswa");
                    nisnya = Integer.toString(niss);
                }else {}
                if (nisTxt.getText().equals(nisnya)){
                    if (sql.next()){
                        kdpd = sql.getInt("Kd_NilaiPd");
                        nis = sql.getInt("Nis_Siswa");
                        String nisString = Integer.toString(nis);
                        nisTxt.setText(nisString);
                        String nama = sql.getString("Nama");
                        namaTxt.setText(nama);
                        double rata = sql.getDouble("Ratarata_Pd");
                        nilaipdTxt.setText(Double.toString(rata));
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Anda memilih siswa yang salah, coba dicek lagi!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_nilaipdTblMouseClicked

    private void nilaisikapTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nilaisikapTblMouseClicked
        // TODO add your handling code here:
        int niss = 0;
        String nisnya = null;
        try {
            int row = nilaisikapTbl.getSelectedRow();
            String kliktabel=(nilaisikapTbl.getModel().getValueAt(row,0).toString());
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaisikap WHERE Kd_NilaiSikap='"+kliktabel+"'");
            java.sql.Statement stmm = conn.createStatement();
            java.sql.ResultSet sqll = stmm.executeQuery("SELECT * FROM tb_nilaisikap WHERE Kd_NilaiSikap='"+kliktabel+"'");
            if (sqll.next()) {
                    niss = sqll.getInt("Nis_siswa");
                    nisnya = Integer.toString(niss);
            }else {}
            if (nisTxt.getText().equals(nisnya)){
                if (sql.next()) {
                    kdsikap = sql.getInt("Kd_NilaiSikap");
                    nis = sql.getInt("Nis_Siswa");
                    String nisString = Integer.toString(nis);
                    nisTxt.setText(nisString);
                    String nama = sql.getString("Nama");
                    namaTxt.setText(nama);
                    double rata = sql.getDouble("Ratarata_Sikap");
                    nilaisikapTxt.setText(Double.toString(rata));
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Anda memilih siswa yang salah, coba dicek lagi!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_nilaisikapTblMouseClicked

    private void nilaiekskulTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nilaiekskulTblMouseClicked
        // TODO add your handling code here:
        int niss = 0;
        String nisnya = null;
        try {
            int row = nilaiekskulTbl.getSelectedRow();
            String kliktabel=(nilaiekskulTbl.getModel().getValueAt(row,0).toString());
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaiekskul WHERE Kd_NilaiEkskul='"+kliktabel+"'");
            java.sql.Statement stmm = conn.createStatement();
            java.sql.ResultSet sqll = stmm.executeQuery("SELECT * FROM tb_nilaiekskul WHERE Kd_NilaiEkskul='"+kliktabel+"'");
            if (sqll.next()) {
                    niss = sqll.getInt("Nis_siswa");
                    nisnya = Integer.toString(niss);
            }else {}
            if (nisTxt.getText().equals(nisnya)){
                if (sql.next()) {
                    kdekskul = sql.getInt("Kd_NilaiEkskul");
                    nis = sql.getInt("Nis_Siswa");
                    String nisString = Integer.toString(nis);
                    nisTxt.setText(nisString);
                    String nama = sql.getString("Nama");
                    namaTxt.setText(nama);
                    double rata = sql.getDouble("Ratarata_Ekskul");
                    nilaiekskulTxt.setText(Double.toString(rata));
                }
            }else{
                 JOptionPane.showMessageDialog(null, "Anda memilih siswa yang salah, coba dicek lagi!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_nilaiekskulTblMouseClicked

    private void siswaTbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siswaTbl2MouseClicked
        // TODO add your handling code here:
        try {
            
            int row = siswaTbl2.getSelectedRow();
            String kliktabel=(siswaTbl2.getModel().getValueAt(row,0).toString());
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT Kd_Nilai, Nis_Siswa, Nama, Nilai_Ratarata, Kelas, Semester, Tahun_Ajaran FROM tb_datanilai WHERE Kd_Nilai='"+kliktabel+"'");
            java.sql.Statement stmm = conn.createStatement();
            java.sql.ResultSet sqll = stmm.executeQuery("SELECT * FROM tb_nilaipd WHERE Kelas='"+kelas+"' AND Semester='"+semester+"' AND Tahun_Ajaran='"+tahunajaran+"'");
            java.sql.Statement stmmm = conn.createStatement();
            java.sql.ResultSet sqlll = stmmm.executeQuery("SELECT * FROM tb_nilaisikap WHERE Kelas='"+kelas+"' AND Semester='"+semester+"' AND Tahun_Ajaran='"+tahunajaran+"'");
            java.sql.Statement stmmmm = conn.createStatement();
            java.sql.ResultSet sqllll = stmmmm.executeQuery("SELECT * FROM tb_nilaiekskul WHERE Kelas='"+kelas+"' AND Semester='"+semester+"' AND Tahun_Ajaran='"+tahunajaran+"'");
            java.sql.Statement stmmmmm = conn.createStatement();
            java.sql.ResultSet sqlllll = stmmmmm.executeQuery("SELECT * FROM tb_nilaikriteria WHERE Kelas='"+kelas+"' AND Semester='"+semester+"' AND Tahun_Ajaran='"+tahunajaran+"'");
            nilaipdTbl.setModel(DbUtils.resultSetToTableModel(sqll));
            nilaisikapTbl.setModel(DbUtils.resultSetToTableModel(sqlll));
            nilaiekskulTbl.setModel(DbUtils.resultSetToTableModel(sqllll));
            nilaikriteriaTbl.setModel(DbUtils.resultSetToTableModel(sqlllll));
            if (sql.next()) {
                kdnilai = sql.getInt("Kd_Nilai");
                nis = sql.getInt("Nis_Siswa");
                String nisString = Integer.toString(nis);
                nisTxt.setText(nisString);
                String nama = sql.getString("Nama");
                namaTxt.setText(nama);
                String kelas = sql.getString("Kelas");
                kelasTxt.setText(kelas);
                String semester = sql.getString("Semester");
                semesterTxt.setText(semester);
                String tahunajaran = sql.getString("Tahun_Ajaran");
                tahunajaranTxt.setText(tahunajaran);
                double rata = sql.getDouble("Nilai_Ratarata");
                nilaiakademikTxt.setText(Double.toString(rata));
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_siswaTbl2MouseClicked

    private void nilaikriteriaTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nilaikriteriaTblMouseClicked
        // TODO add your handling code here:
        try {
            int row = nilaikriteriaTbl.getSelectedRow();
            String kliktabel=(nilaikriteriaTbl.getModel().getValueAt(row,0).toString());
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT nk.kd_kriteria, nk.nis_siswa, nk.nama, npd.Ratarata_Pd, ns.Ratarata_Sikap, "
                    + "ne.Ratarata_Ekskul, nk.absensi, dn.Nilai_Ratarata, nk.kelas, nk.semester, nk.tahun_ajaran from (tb_nilaikriteria nk "
                    + "left JOIN tb_nilaipd npd on nk.kd_nilaipd = npd.kd_nilaipd) LEFT JOIN tb_nilaisikap ns on nk.kd_nilaisikap = ns.kd_nilaisikap "
                    + "LEFT JOIN tb_nilaiekskul ne on nk.kd_nilaiekskul = ne.kd_nilaiekskul LEFT JOIN tb_datanilai dn on nk.kd_nilai = dn.kd_nilai WHERE "
                    + "kd_kriteria='"+kliktabel+"'");
            if (sql.next()) {
                kd_kriteria = sql.getInt("kd_kriteria");
                String Skdkriteria = Integer.toString(kd_kriteria);
                kdnilaikriteriaTxt.setText(Skdkriteria);
                int nis = sql.getInt("Nis_Siswa");
                String nisString = Integer.toString(nis);
                nisTxt.setText(nisString);
                String nama = sql.getString("Nama");
                namaTxt.setText(nama);
                String kelas = sql.getString("Kelas");
                kelasTxt.setText(kelas);
                String semester = sql.getString("Semester");
                semesterTxt.setText(semester);
                String tahunajaran = sql.getString("Tahun_Ajaran");
                tahunajaranTxt.setText(tahunajaran);
                String n1 = sql.getString(4);
                String n2 = sql.getString(5);
                String n3 = sql.getString(6);
                String n4 = sql.getString(7);
                String n5 = sql.getString(8);
                nilaipdTxt.setText(n1);
                nilaisikapTxt.setText(n2);
                nilaiekskulTxt.setText(n3);
                nilaiakademikTxt.setText(n5);
                
                if(n4.equals("1.0")){
                    absensiCmb.setSelectedIndex(1);}
               else if(n4.equals("2.0")){
                    absensiCmb.setSelectedIndex(2);}
               else if(n4.equals("3.0")){
                    absensiCmb.setSelectedIndex(3);}
               else if(n4.equals("4.0")){
                    absensiCmb.setSelectedIndex(4);}
               else if(n4.equals("5.0")){
                    absensiCmb.setSelectedIndex(5);}
               absensiTxt.setText(n4);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        kdnilaikriteriaTxt.setEnabled(false);
    }//GEN-LAST:event_nilaikriteriaTblMouseClicked

    private void absensiCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absensiCmbActionPerformed
        // TODO add your handling code here:
        String k1 = "";
        if (absensiCmb.getSelectedIndex()==0){
            k1="";}
        else if(absensiCmb.getSelectedIndex()==1){
            k1="1.0";}
        else if(absensiCmb.getSelectedIndex()==2){
            k1="2.0";}
        else if(absensiCmb.getSelectedIndex()==3){
            k1="3.0";}
        else if(absensiCmb.getSelectedIndex()==4){
            k1="4.0";}
        else if(absensiCmb.getSelectedIndex()==5){
            k1="5.0";}
        absensiTxt.setText(k1);
    }//GEN-LAST:event_absensiCmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Kriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Kriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Kriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Kriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Kriteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> absensiCmb;
    private javax.swing.JTextField absensiTxt;
    private javax.swing.JPanel akademikPnl;
    private javax.swing.JButton bersihkanBtn;
    private javax.swing.JTextField cari1Txt;
    private javax.swing.JPanel ekskulPnl;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField kdnilaikriteriaTxt;
    private javax.swing.JComboBox<String> kelasCmb;
    private javax.swing.JTextField kelasTxt;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTextField nilaiakademikTxt;
    private javax.swing.JTable nilaiekskulTbl;
    private javax.swing.JTextField nilaiekskulTxt;
    private javax.swing.JTable nilaikriteriaTbl;
    private javax.swing.JTable nilaipdTbl;
    private javax.swing.JTextField nilaipdTxt;
    private javax.swing.JTable nilaisikapTbl;
    private javax.swing.JTextField nilaisikapTxt;
    private javax.swing.JTextField nisTxt;
    private javax.swing.JPanel pdPnl;
    private javax.swing.JButton refresh1Btn;
    private javax.swing.JComboBox<String> semesterCmb;
    private javax.swing.JTextField semesterTxt;
    private javax.swing.JPanel sikapPnl;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JTable siswaTbl2;
    private javax.swing.JComboBox<String> tahunajaranCmb;
    private javax.swing.JTextField tahunajaranTxt;
    private javax.swing.JButton tampilkan1Btn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
