/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_spk_saw;

import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ferdy
 */
public class Form_Nilai_PD extends javax.swing.JFrame {

    int nis = 0;
    int kd_nilaipd = 0;
    double n1,n2,kd1,kd2;
    double rata;
    String kelas = "";
    String semester = "";
    String tahunajaran = "";
    String kategori2 = "";
    
   
    private void getDataSiswa() {
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datasiswa");
            datasiswaTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
    }
    
    
    private void getNilaiPdSiswa() {
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaipd");
            nilaipdTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
    }
    
    private void getCariNilaiPdSiswa() {
        if (kategori2.equals("") || cari2Txt.getText().equals("")){
            try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaipd");
            nilaipdTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
        } else {
            try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaipd WHERE "+kategori2+" like '%"+cari2Txt.getText()+"%'");
            nilaipdTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
    }
        }
    }
    
    /**
     * Creates new form Form_Nilai_Non_Akademik
     */
    public Form_Nilai_PD() {
        initComponents();
        getNilaiPdSiswa();
        getDataSiswa();
        nisTxt.setEditable(false);
        namaTxt.setEditable(false);
        cari1Txt.setEditable(false);
        tahunajaranTxt.setEditable(false);
        muhadrohTxt.setEditable(false);
        tahfizhTxt.setEditable(false);
        ratarata.setEditable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tahunajaranTxt = new javax.swing.JTextField();
        namaTxt = new javax.swing.JTextField();
        nisTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        muhadrohCmb = new javax.swing.JComboBox<>();
        tahfizhCmb = new javax.swing.JComboBox<>();
        proses1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        muhadrohTxt = new javax.swing.JTextField();
        tahfizhTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ratarata = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        kdnilaipdTxt = new javax.swing.JTextField();
        simpanBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        bersihkanBtn = new javax.swing.JButton();
        kelasCmb = new javax.swing.JComboBox<>();
        semesterCmb = new javax.swing.JComboBox<>();
        tahunajaranCmb = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cari1Txt = new javax.swing.JTextField();
        cari1Btn = new javax.swing.JButton();
        refresh1Btn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        datasiswaTbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        refresh2Btn = new javax.swing.JButton();
        kategoricari2Cmb = new javax.swing.JComboBox<>();
        cari2Txt = new javax.swing.JTextField();
        cari2Btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        nilaipdTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Nilai Percaya Diri");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nilai Pd"));

        jLabel1.setText("NIS");

        jLabel2.setText("Nama");

        jLabel3.setText("Kelas");

        jLabel4.setText("Semester");

        jLabel5.setText("Tahun Ajaran");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Help.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Percaya Diri"));

        jLabel6.setText("Muhadroh");

        jLabel7.setText("Tahfizh");

        muhadrohCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Sangat Baik (A)", "Baik (B)", "Cukup Baik (C)", "Buruk (D)", "Sangat Buruk (E)" }));
        muhadrohCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muhadrohCmbActionPerformed(evt);
            }
        });

        tahfizhCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Sangat Baik (A)", "Baik (B)", "Cukup Baik (C)", "Buruk (D)", "Sangat Buruk (E)" }));
        tahfizhCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahfizhCmbActionPerformed(evt);
            }
        });

        proses1.setText("Proses");
        proses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proses1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Grade");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Nilai");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Rata-rata");

        jLabel9.setText("Kode Nilai PD");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(proses1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(23, 23, 23)
                        .addComponent(tahfizhCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(muhadrohCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ratarata, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tahfizhTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(muhadrohTxt)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(kdnilaipdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kdnilaipdTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muhadrohTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(muhadrohCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tahfizhCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tahfizhTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proses1)
                    .addComponent(jLabel8)
                    .addComponent(ratarata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        simpanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Upload.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        hapusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        bersihkanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clear.png"))); // NOI18N
        bersihkanBtn.setText("Clear");
        bersihkanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanBtnActionPerformed(evt);
            }
        });

        kelasCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "VII-A", "VII-B", "VIII-A", "VIII-B", "IX-A", "IX-B" }));
        kelasCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasCmbActionPerformed(evt);
            }
        });

        semesterCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Ganjil", "Genap" }));
        semesterCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterCmbActionPerformed(evt);
            }
        });

        tahunajaranCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "2018/2019", "2019/2020", "2020/2021", "2021/2022", "2022/2023", "2023/2024", "Input Manual" }));
        tahunajaranCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunajaranCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(namaTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpanBtn)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(updateBtn)
                                .addGap(18, 18, 18)
                                .addComponent(hapusBtn)
                                .addGap(18, 18, 18)
                                .addComponent(bersihkanBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tahunajaranCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tahunajaranTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(kelasCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(semesterCmb, 0, 83, Short.MAX_VALUE)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kelasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semesterCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tahunajaranCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tahunajaranTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanBtn)
                    .addComponent(updateBtn)
                    .addComponent(hapusBtn)
                    .addComponent(bersihkanBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Cari NIS atau Nama Siswa");

        cari1Txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cari1Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cari1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        cari1Btn.setText("Cari");
        cari1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari1BtnActionPerformed(evt);
            }
        });

        refresh1Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refresh1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        refresh1Btn.setText("Refresh");
        refresh1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1BtnActionPerformed(evt);
            }
        });

        datasiswaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Tanggal Lahir", "Jenis Kelamin"
            }
        ));
        datasiswaTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datasiswaTblMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(datasiswaTbl);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(cari1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cari1Btn)
                        .addGap(18, 18, 18)
                        .addComponent(refresh1Btn)
                        .addContainerGap(40, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cari1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari1Btn)
                    .addComponent(refresh1Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Siswa", jPanel5);

        refresh2Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refresh2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        refresh2Btn.setText("Refresh");
        refresh2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh2BtnActionPerformed(evt);
            }
        });

        kategoricari2Cmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kategoricari2Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Kategori Pencarian-", "NIS", "Nama", "Kelas", "Semester", "Tahun Ajaran" }));
        kategoricari2Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoricari2CmbActionPerformed(evt);
            }
        });

        cari2Txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cari2Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cari2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        cari2Btn.setText("Cari");
        cari2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari2BtnActionPerformed(evt);
            }
        });

        nilaipdTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd Nilai Pd", "Nis", "Nama", "Muhadroh", "Tahfizh", "Rata-rata", "Kelas", "Semester", "Tahun Ajaran"
            }
        ));
        nilaipdTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nilaipdTblMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(nilaipdTbl);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );

        jScrollPane1.setViewportView(jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kategoricari2Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cari2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cari2Btn)
                .addGap(18, 18, 18)
                .addComponent(refresh2Btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategoricari2Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari2Btn)
                    .addComponent(refresh2Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Nilai PercayaDiri", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Data Nilai Non Akademik");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Lihat petunjuk pada tampilan utama aplikasi ini.","Petunjuk",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void proses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proses1ActionPerformed
        // TODO add your handling code here:
        if(muhadrohTxt.getText().equals("") || tahfizhTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Silakan diinput nilai pdnya.","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }else{
            n1 = Double.parseDouble(muhadrohTxt.getText());
            n2 = Double.parseDouble(tahfizhTxt.getText());
            double jumlah = n1+n2;
            rata = jumlah/2;
            ratarata.setText(Double.toString(rata));
        }
    }//GEN-LAST:event_proses1ActionPerformed

    private void kategoricari2CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoricari2CmbActionPerformed
        // TODO add your handling code here:
        if (kategoricari2Cmb.getSelectedIndex()==0){ 
        kategori2="";}
        else if(kategoricari2Cmb.getSelectedIndex()==1){
        kategori2="Nis_Siswa";}
        else if(kategoricari2Cmb.getSelectedIndex()==2){
        kategori2="Nama";}
        else if(kategoricari2Cmb.getSelectedIndex()==3){
        kategori2="Kelas";}
        else if(kategoricari2Cmb.getSelectedIndex()==4){
        kategori2="Semester";}
        else if(kategoricari2Cmb.getSelectedIndex()==5){
        kategori2="Tahun_Ajaran";}
    }//GEN-LAST:event_kategoricari2CmbActionPerformed

    private void cari2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2BtnActionPerformed
        // TODO add your handling code here:
        if (kategori2.equals("")){
            JOptionPane.showMessageDialog(null, "Pilih kategori pencarian terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaipd WHERE "+kategori2+" like '%"+cari2Txt.getText()+"%'");
                nilaipdTbl.setModel(DbUtils.resultSetToTableModel(sql));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_cari2BtnActionPerformed

    private void refresh2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh2BtnActionPerformed
        // TODO add your handling code here:
        cari2Txt.setText("");
        kategoricari2Cmb.setSelectedIndex(0);
        getNilaiPdSiswa();
    }//GEN-LAST:event_refresh2BtnActionPerformed

    private void nilaipdTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nilaipdTblMouseClicked
        // TODO add your handling code here:
        try {
            int row = nilaipdTbl.getSelectedRow();
            String kliktabel=(nilaipdTbl.getModel().getValueAt(row,0).toString());
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaipd WHERE Kd_NilaiPd='"+kliktabel+"'");

            if (sql.next()) {
                kd_nilaipd = sql.getInt("Kd_NilaiPd");
                String Skdnilaipd = Integer.toString(kd_nilaipd);
                kdnilaipdTxt.setText(Skdnilaipd);
                nis = sql.getInt("Nis_Siswa");
                String nisString = Integer.toString(nis);
                nisTxt.setText(nisString);
                String nama = sql.getString("Nama");
                namaTxt.setText(nama);
                Double rata = sql.getDouble("Ratarata_Pd");
                ratarata.setText(Double.toString(rata));
                double n1 = sql.getDouble("Muhadroh");
                double n2 = sql.getDouble("Tahfizh");
                String n1s = Double.toString(n1);
                String n2s = Double.toString(n2);
                
                if(n1s.equals("4.0")){
                    muhadrohCmb.setSelectedIndex(1);}
               else if(n1s.equals("3.0")){
                    muhadrohCmb.setSelectedIndex(2);}
               else if(n1s.equals("2.0")){
                    muhadrohCmb.setSelectedIndex(3);}
               else if(n1s.equals("1.0")){
                    muhadrohCmb.setSelectedIndex(4);}
               else if(n1s.equals("0.0")){
                    muhadrohCmb.setSelectedIndex(5);}
               muhadrohTxt.setText(n1s);
               
               if(n2s.equals("4.0")){
                    tahfizhCmb.setSelectedIndex(1);}
               else if(n2s.equals("3.0")){
                    tahfizhCmb.setSelectedIndex(2);}
               else if(n2s.equals("2.0")){
                    tahfizhCmb.setSelectedIndex(3);}
               else if(n2s.equals("1.0")){
                    tahfizhCmb.setSelectedIndex(4);}
               else if(n2s.equals("0.0")){
                    tahfizhCmb.setSelectedIndex(5);}
               tahfizhTxt.setText(n2s);
               
               String kls = sql.getString("Kelas");
                if(kls.equals("")){
                    kelasCmb.setSelectedIndex(0);}
                else if(kls.equals("VII-A")){
                    kelasCmb.setSelectedIndex(1);}
                else if(kls.equals("VII-B")){
                    kelasCmb.setSelectedIndex(2);}
                else if(kls.equals("VIII-A")){
                    kelasCmb.setSelectedIndex(3);}
                else if(kls.equals("VIII-B")){
                    kelasCmb.setSelectedIndex(4);}
                else if(kls.equals("IX-A")){
                    kelasCmb.setSelectedIndex(5);}
                else if(kls.equals("IX-B")){
                    kelasCmb.setSelectedIndex(6);}

                String smstr = sql.getString("Semester");
                if(smstr.equals("")){
                    semesterCmb.setSelectedIndex(0);}
                else if(smstr.equals("Ganjil")){
                    semesterCmb.setSelectedIndex(1);}
                else if(smstr.equals("Genap")){
                    semesterCmb.setSelectedIndex(2);}

                String thnajaran = sql.getString("Tahun_Ajaran");
                if(thnajaran.equals("")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(0);}
                else if(thnajaran.equals("2018/2019")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(1);}
                else if(thnajaran.equals("2019/2020")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(2);}
                else if(thnajaran.equals("2020/2021")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(3);}
                else if(thnajaran.equals("2021/2022")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(4);}
                else if(thnajaran.equals("2022/2023")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(5);}
                else if(thnajaran.equals("2023/2024")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(6);}
                else{
                    tahunajaranTxt.setEnabled(true);
                    tahunajaranTxt.setText(thnajaran);
                    tahunajaranCmb.setSelectedIndex(7);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        kdnilaipdTxt.setEnabled(false);
    }//GEN-LAST:event_nilaipdTblMouseClicked

    private void muhadrohCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muhadrohCmbActionPerformed
        // TODO add your handling code here:
        String k1 = "";
        if (muhadrohCmb.getSelectedIndex()==0){ 
            k1="";}
        else if(muhadrohCmb.getSelectedIndex()==1){
            k1="4.0";}
        else if(muhadrohCmb.getSelectedIndex()==2){
            k1="3.0";}
        else if(muhadrohCmb.getSelectedIndex()==3){
            k1="2.0";}
        else if(muhadrohCmb.getSelectedIndex()==4){
            k1="1.0";}
        else if(muhadrohCmb.getSelectedIndex()==5){
            k1="0.0";}
        muhadrohTxt.setText(k1);
    }//GEN-LAST:event_muhadrohCmbActionPerformed

    private void tahfizhCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahfizhCmbActionPerformed
        // TODO add your handling code here:
        String k2 = "";
        if (tahfizhCmb.getSelectedIndex()==0){ 
            k2="";}
        else if(tahfizhCmb.getSelectedIndex()==1){
            k2="4.0";}
        else if(tahfizhCmb.getSelectedIndex()==2){
            k2="3.0";}
        else if(tahfizhCmb.getSelectedIndex()==3){
            k2="2.0";}
        else if(tahfizhCmb.getSelectedIndex()==4){
            k2="1.0";}
        else if(tahfizhCmb.getSelectedIndex()==5){
            k2="0.0";}
        tahfizhTxt.setText(k2);
    }//GEN-LAST:event_tahfizhCmbActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        String nisnya = null;
        String namanya = null;
        String kelasnya = null;
        String semesternya = null;
        
        if (kelasCmb.getSelectedIndex()==0){
            kelas="";}
        else if(kelasCmb.getSelectedIndex()==1){
            kelas="VII-A";}
        else if(kelasCmb.getSelectedIndex()==2){
            kelas="VII-B";}
        else if(kelasCmb.getSelectedIndex()==3){
            kelas="VIII-A";}
        else if(kelasCmb.getSelectedIndex()==4){
            kelas="VIII-B";}
        else if(kelasCmb.getSelectedIndex()==5){
            kelas="IX-A";}
        else if(kelasCmb.getSelectedIndex()==6){
            kelas="IX-B";}

        if (semesterCmb.getSelectedIndex()==0){
            semester="";}
        else if(semesterCmb.getSelectedIndex()==1){
            semester="Ganjil";}
        else if(semesterCmb.getSelectedIndex()==2){
            semester="Genap";}

        if (tahunajaranCmb.getSelectedIndex()==0){
            tahunajaran="";}
        else if(tahunajaranCmb.getSelectedIndex()==1){
            tahunajaran="2018/2019";}
        else if(tahunajaranCmb.getSelectedIndex()==2){
            tahunajaran="2019/2020";}
        else if(tahunajaranCmb.getSelectedIndex()==3){
            tahunajaran="2020/2021";}
        else if(tahunajaranCmb.getSelectedIndex()==4){
            tahunajaran="2021/2022";}
        else if(tahunajaranCmb.getSelectedIndex()==5){
            tahunajaran="2022/2023";}
        else if(tahunajaranCmb.getSelectedIndex()==6){
            tahunajaran="2023/2024";}
        else if(tahunajaranCmb.getSelectedIndex()==7){
            tahunajaran=tahunajaranTxt.getText();}
        
        if (kdnilaipdTxt.getText().equals("") ||nisTxt.getText().equals("") || namaTxt.getText().equals("") || kelas.equals("") || semester.equals("") || tahunajaran.equals("")
                || muhadrohTxt.getText().equals("") || tahfizhTxt.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }else {
            kd1 = Double.parseDouble(muhadrohTxt.getText());
            kd2 = Double.parseDouble(tahfizhTxt.getText());
           try {
           java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
           java.sql.Statement stm = conn.createStatement();
           java.sql.ResultSet sqll = stm.executeQuery("SELECT Nis_Siswa, Nama, Kelas, Semester FROM tb_nilaipd WHERE Nis_Siswa='"+nisTxt.getText()+"' AND Kelas='"+kelas+"' AND Semester='"+semester+"'");        
           if (sqll.next()) {
               nis = sqll.getInt("Nis_Siswa");
               nisnya = Integer.toString(nis);
               namanya = sqll.getString("Nama");
               kelasnya = sqll.getString("Kelas");
               semesternya = sqll.getString("Semester");
           } else {}
           if (nisTxt.getText().equals(nisnya) && kelas.equals(kelasnya) && semester.equals(semesternya)){
           JOptionPane.showMessageDialog(null, "Nilai PD "+namaTxt.getText()+" kelas "+kelas+" pada semester "+semester+" sudah ada!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);    
           }else {         
                String sql = "INSERT INTO tb_nilaipd VALUES('"+kdnilaipdTxt.getText()+"','"+nisTxt.getText()+"','"+namaTxt.getText()+"','"+kd1+"','"+kd2+"','"+rata+"','"+kelas+"','"+semester+"','"+tahunajaran+"')";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Nilai Pd siswa berhasil disimpan!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
           }
            } catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Nilai Pd siswa gagal disimpan!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
           getNilaiPdSiswa();
           kd_nilaipd = 0;
           nisTxt.setText("");
        namaTxt.setText("");
        kelasCmb.setSelectedIndex(0);
        semesterCmb.setSelectedIndex(0);
        tahunajaranCmb.setSelectedIndex(0);
        kdnilaipdTxt.setText("");
        tahunajaranTxt.setText("");
        muhadrohCmb.setSelectedIndex(0);
        tahfizhCmb.setSelectedIndex(0);
        muhadrohTxt.setText("");
        tahfizhTxt.setText("");
        ratarata.setText("");
        }
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
         String kelas = null;
        if (kelasCmb.getSelectedIndex()==0){
            kelas="";}
        else if(kelasCmb.getSelectedIndex()==1){
            kelas="VII-A";}
        else if(kelasCmb.getSelectedIndex()==2){
            kelas="VII-B";}
        else if(kelasCmb.getSelectedIndex()==3){
            kelas="VIII-A";}
        else if(kelasCmb.getSelectedIndex()==4){
            kelas="VIII-B";}
        else if(kelasCmb.getSelectedIndex()==5){
            kelas="IX-A";}
        else if(kelasCmb.getSelectedIndex()==6){
            kelas="IX-B";}

        String semester = null;
        if (semesterCmb.getSelectedIndex()==0){
            semester="";}
        else if(semesterCmb.getSelectedIndex()==1){
            semester="Ganjil";}
        else if(semesterCmb.getSelectedIndex()==2){
            semester="Genap";}

        String tahunajaran = null;
        if (tahunajaranCmb.getSelectedIndex()==0){
            tahunajaran="";}
        else if(tahunajaranCmb.getSelectedIndex()==1){
            tahunajaran="2018/2019";}
        else if(tahunajaranCmb.getSelectedIndex()==2){
            tahunajaran="2019/2020";}
        else if(tahunajaranCmb.getSelectedIndex()==3){
            tahunajaran="2020/2021";}
        else if(tahunajaranCmb.getSelectedIndex()==4){
            tahunajaran="2021/2022";}
        else if(tahunajaranCmb.getSelectedIndex()==5){
            tahunajaran="2022/2023";}
        else if(tahunajaranCmb.getSelectedIndex()==6){
            tahunajaran="2023/2024";}
        else if(tahunajaranCmb.getSelectedIndex()==7){
            tahunajaran=tahunajaranTxt.getText();}
        
        if (kd_nilaipd == 0){
            JOptionPane.showMessageDialog(null, "Pilih nilai PD siswa yang ingin diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }else{
            if (nisTxt.getText().equals("") || namaTxt.getText().equals("") || kelas.equals("") || semester.equals("") || tahunajaran.equals("")
                    || muhadrohTxt.getText().equals("") || tahfizhTxt.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            }else {
                kd1 = Double.parseDouble(muhadrohTxt.getText());
                kd2 = Double.parseDouble(tahfizhTxt.getText());
                try {
                    java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                    String sql = "UPDATE tb_nilaipd SET Nis_Siswa='"+nisTxt.getText()+"', Nama='"+namaTxt.getText()+"', Muhadroh='"+kd1+"', Tahfizh='"+kd2+"',Ratarata_Pd ='"+rata+"',"
                            + " Kelas='"+kelas+"', Semester='"+semester+"', Tahun_Ajaran='"+tahunajaran+"' WHERE Kd_NilaiPd='"+kd_nilaipd+"'";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Nilai PD siswa berhasil diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);

                }catch (SQLException | HeadlessException e){
                    JOptionPane.showMessageDialog(null, "Nilai PD siswa gagal diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        getCariNilaiPdSiswa();
        kd_nilaipd = 0;
        kdnilaipdTxt.setEnabled(true);
        nisTxt.setText("");
        namaTxt.setText("");
        kelasCmb.setSelectedIndex(0);
        semesterCmb.setSelectedIndex(0);
        tahunajaranCmb.setSelectedIndex(0);
        kdnilaipdTxt.setText("");
        tahunajaranTxt.setText("");
        muhadrohCmb.setSelectedIndex(0);
        tahfizhCmb.setSelectedIndex(0);
        muhadrohTxt.setText("");
        tahfizhTxt.setText("");
        ratarata.setText("");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        // TODO add your handling code here:
        if (kd_nilaipd == 0){
            JOptionPane.showMessageDialog(null, "Pilih Nilai PD siswa yang ingin dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            Object[] options = {"Iya", "Tidak"};
            int van = JOptionPane.showOptionDialog(this, "Anda yakin ingin menghapus data Nilai PD "+namaTxt.getText()+"?",
            "Konfirmasi", JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            if(van== 0){
                try {
                    java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                    String sql = "DELETE FROM tb_nilaipd WHERE Kd_NilaiPd='"+kd_nilaipd+"'";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Nilai PD siswa berhasil dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException | HeadlessException e) {
                    JOptionPane.showMessageDialog(null, "Nilai PD siswa gagal dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                }
                getCariNilaiPdSiswa();}
            else if(van== 1){
            }
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void bersihkanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanBtnActionPerformed
        // TODO add your handling code here:
        kd_nilaipd = 0;
        kdnilaipdTxt.setEnabled(true);
        nisTxt.setText("");
        namaTxt.setText("");
        kelasCmb.setSelectedIndex(0);
        semesterCmb.setSelectedIndex(0);
        tahunajaranCmb.setSelectedIndex(0);
        kdnilaipdTxt.setText("");
        tahunajaranTxt.setText("");
        muhadrohCmb.setSelectedIndex(0);
        tahfizhCmb.setSelectedIndex(0);
        muhadrohTxt.setText("");
        tahfizhTxt.setText("");
        ratarata.setText("");
    }//GEN-LAST:event_bersihkanBtnActionPerformed

    private void cari1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari1BtnActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datasiswa WHERE Nis_Siswa like '%"+cari1Txt.getText()+"%' or Nama like '%"+cari1Txt.getText()+"%'");
            datasiswaTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cari1BtnActionPerformed

    private void refresh1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1BtnActionPerformed
        // TODO add your handling code here:
        getDataSiswa();
        cari1Txt.setText("");
    }//GEN-LAST:event_refresh1BtnActionPerformed

    private void datasiswaTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datasiswaTblMouseClicked
        // TODO add your handling code here:
        try {
            int row = datasiswaTbl.getSelectedRow();
            String kliktabel=(datasiswaTbl.getModel().getValueAt(row,0).toString());
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT Nis_Siswa, Nama FROM tb_datasiswa WHERE Nis_siswa='"+kliktabel+"'");

            if (sql.next()) {
                nis = sql.getInt("Nis_siswa");
                String nisString = Integer.toString(nis);
                nisTxt.setText(nisString);
                String nama = sql.getString("Nama");
                namaTxt.setText(nama);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_datasiswaTblMouseClicked

    private void kelasCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasCmbActionPerformed
        // TODO add your handling code here:
        if (kelasCmb.getSelectedIndex()==0){
            kelas="";}
        else if(kelasCmb.getSelectedIndex()==1){
            kelas="VII-A";}
        else if(kelasCmb.getSelectedIndex()==2){
            kelas="VII-B";}
        else if(kelasCmb.getSelectedIndex()==3){
            kelas="VIII-A";}
        else if(kelasCmb.getSelectedIndex()==4){
            kelas="VIII-B";}
        else if(kelasCmb.getSelectedIndex()==5){
            kelas="IX-A";}
        else if(kelasCmb.getSelectedIndex()==6){
            kelas="IX-B";}
    }//GEN-LAST:event_kelasCmbActionPerformed

    private void semesterCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterCmbActionPerformed
        // TODO add your handling code here:
        if (semesterCmb.getSelectedIndex()==0){
            semester="";}
        else if(semesterCmb.getSelectedIndex()==1){
            semester="Ganjil";}
        else if(semesterCmb.getSelectedIndex()==2){
            semester="Genap";}
    }//GEN-LAST:event_semesterCmbActionPerformed

    private void tahunajaranCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunajaranCmbActionPerformed
        // TODO add your handling code here:\
        if (tahunajaranCmb.getSelectedIndex()==0){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==1){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==2){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==3){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==4){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==5){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==6){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==7){
            tahunajaranTxt.setEnabled(true);}
    }//GEN-LAST:event_tahunajaranCmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_PD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_PD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_PD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_PD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Nilai_PD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bersihkanBtn;
    private javax.swing.JButton cari1Btn;
    private javax.swing.JTextField cari1Txt;
    private javax.swing.JButton cari2Btn;
    private javax.swing.JTextField cari2Txt;
    private javax.swing.JTable datasiswaTbl;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> kategoricari2Cmb;
    private javax.swing.JTextField kdnilaipdTxt;
    private javax.swing.JComboBox<String> kelasCmb;
    private javax.swing.JComboBox<String> muhadrohCmb;
    private javax.swing.JTextField muhadrohTxt;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTable nilaipdTbl;
    private javax.swing.JTextField nisTxt;
    private javax.swing.JButton proses1;
    private javax.swing.JTextField ratarata;
    private javax.swing.JButton refresh1Btn;
    private javax.swing.JButton refresh2Btn;
    private javax.swing.JComboBox<String> semesterCmb;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JComboBox<String> tahfizhCmb;
    private javax.swing.JTextField tahfizhTxt;
    private javax.swing.JComboBox<String> tahunajaranCmb;
    private javax.swing.JTextField tahunajaranTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
