/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_spk_saw;

import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.text.SimpleDateFormat;



/**
 *
 * @author Ferdy
 */
public class Form_Data_Siswa extends javax.swing.JFrame {
    String nisString;
    String jns_kelamin = "";
    String tgl_lahir;
    int nis = 0;
    
    private void getData() {
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datasiswa");
            datasiswaTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void getCariData() {
        if (cariTxt.getText().equals("")){
            try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datasiswa");
            datasiswaTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datasiswa WHERE Nis_Siswa like '%"+cariTxt.getText()+"%' or Nama like '%"+cariTxt.getText()+"%'");
            datasiswaTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    /**
     * Creates new form Form_Data_Mahasiswa
     */
    public Form_Data_Siswa() {
        initComponents();
        getData();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nisTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namaTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jeniskelaminCmb = new javax.swing.JComboBox<>();
        simpanBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        bersihkanBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cariTxt = new javax.swing.JTextField();
        cariBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datasiswaTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Data Siswa");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/computer.png")).getImage());
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Biodata Siswa"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("NIS");

        nisTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nama");

        namaTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jeniskelaminCmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jeniskelaminCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Laki-Laki", "Perempuan" }));

        simpanBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        simpanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Upload.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        hapusBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hapusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        bersihkanBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bersihkanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clear.png"))); // NOI18N
        bersihkanBtn.setText("Clear");
        bersihkanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaTxt)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 120, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)
                                .addComponent(jeniskelaminCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 182, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(simpanBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapusBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bersihkanBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jeniskelaminCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanBtn)
                    .addComponent(updateBtn)
                    .addComponent(hapusBtn)
                    .addComponent(bersihkanBtn))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Data Siswa"));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Cari NIS atau Nama Siswa");

        cariTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cariBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cariBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        cariBtn.setText("Cari");
        cariBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtnActionPerformed(evt);
            }
        });

        refreshBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        datasiswaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Jenis Kelamin"
            }
        ));
        datasiswaTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datasiswaTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(datasiswaTbl);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 660, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(cariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(refreshBtn)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBtn)
                    .addComponent(refreshBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datasiswa WHERE Nis_Siswa like '%"+cariTxt.getText()+"%' or Nama like '%"+cariTxt.getText()+"%'");
            datasiswaTbl.setModel(DbUtils.resultSetToTableModel(sql));   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cariBtnActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
     
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        getData();
        cariTxt.setText("");
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void bersihkanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanBtnActionPerformed
        // TODO add your handling code here:
        nis = 0;
        nisTxt.setText("");
        namaTxt.setText("");
        jeniskelaminCmb.setSelectedIndex(0);   
    }//GEN-LAST:event_bersihkanBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        // TODO add your handling code here:
        if (nis == 0){
            JOptionPane.showMessageDialog(null, "Pilih dahulu data siswa yang ingin dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            Object[] options = {"Iya", "Tidak"};
            int van = JOptionPane.showOptionDialog(this, "Anda yakin ingin menghapus data siswa "+namaTxt.getText()+"?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            if(van== 0){
                try {
                    String sql = "DELETE FROM tb_datasiswa WHERE Nis_Siswa='"+nisString+"'";
                    java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Data siswa berhasil dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                    nisTxt.setText("");
                    namaTxt.setText("");
                    jeniskelaminCmb.setSelectedIndex(0);  
                } catch (SQLException | HeadlessException e) {
                    JOptionPane.showMessageDialog(null, "Data siswa gagal dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                }
                getCariData();
            } else if(van== 1){
            }
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if (nis == 0){
            JOptionPane.showMessageDialog(null, "Pilih dahulu data siswa yang ingin diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (jeniskelaminCmb.getSelectedIndex()==0){
                jns_kelamin="";}
            else if(jeniskelaminCmb.getSelectedIndex()==1){
                jns_kelamin="Laki-laki";}
            else if(jeniskelaminCmb.getSelectedIndex()==2){
                jns_kelamin="Perempuan";}
            if (nisTxt.getText().equals("") || namaTxt.getText().equals("") || jns_kelamin.equals("")) {
                JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {
                    String sql = "UPDATE tb_datasiswa set Nis_Siswa='"+nisTxt.getText()+"',Nama='"+namaTxt.getText()+"',Jenis_Kelamin='"+jns_kelamin+"'where Nis_Siswa='"+nisString+"'";
                    java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Data siswa berhasil diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                    nisTxt.setText("");
                    namaTxt.setText("");
                    jeniskelaminCmb.setSelectedIndex(0);  
                } catch (SQLException | HeadlessException e){
                    JOptionPane.showMessageDialog(null, "Data siswa gagal diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                }
                getCariData();
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        String nisnya = "";
        String namanya = "";

        if (jeniskelaminCmb.getSelectedIndex()==0){
            jns_kelamin="";}
        else if(jeniskelaminCmb.getSelectedIndex()==1){
            jns_kelamin="Laki-laki";}
        else if(jeniskelaminCmb.getSelectedIndex()==2){
            jns_kelamin="Perempuan";}

        
        if (nisTxt.getText().equals("") || namaTxt.getText().equals("") || jns_kelamin.equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet sqll = stm.executeQuery("SELECT Nis_Siswa, Nama FROM tb_datasiswa WHERE Nis_Siswa='"+nisTxt.getText()+"'");
                if (sqll.next()) {
                    nis = sqll.getInt("Nis_Siswa");
                    nisnya = Integer.toString(nis);
                    namanya = sqll.getString("Nama");
                } else {}
                if (nisTxt.getText().equals(nisnya)){
                    JOptionPane.showMessageDialog(null, "Data siswa dengan NIS "+nisTxt.getText()+" sudah ada, dengan nama "+namanya+"!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                } else {
                    String sql = "INSERT INTO tb_datasiswa VALUES('"+nisTxt.getText()+"','"+namaTxt.getText()+"','"+jns_kelamin+"')";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Data siswa berhasil disimpan!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                    nisTxt.setText("");
                    namaTxt.setText("");
                    jeniskelaminCmb.setSelectedIndex(0);  
                }
            } catch (SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Data siswa gagal disimpan!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        getData();
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void datasiswaTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datasiswaTblMouseClicked
        // TODO add your handling code here:
        try {
            int row = datasiswaTbl.getSelectedRow();
            String kliktabel=(datasiswaTbl.getModel().getValueAt(row,0).toString());
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datasiswa WHERE Nis_Siswa='"+kliktabel+"' order by Nis_Siswa desc");

            if (sql.next()) {
                nis = sql.getInt("Nis_Siswa");
                nisString = Integer.toString(nis);
                nisTxt.setText(nisString);
                String nama = sql.getString("Nama");
                namaTxt.setText(nama);
                String jeniskelamin = sql.getString("Jenis_Kelamin");
                if(jeniskelamin.equals("")){
                    jeniskelaminCmb.setSelectedIndex(0);}
                else if(jeniskelamin.equals("Laki-laki")){
                    jeniskelaminCmb.setSelectedIndex(1);}
                else if(jeniskelamin.equals("Perempuan")){
                    jeniskelaminCmb.setSelectedIndex(2);}
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_datasiswaTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Data_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Data_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Data_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Data_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Data_Siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bersihkanBtn;
    private javax.swing.JButton cariBtn;
    private javax.swing.JTextField cariTxt;
    private javax.swing.JTable datasiswaTbl;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jeniskelaminCmb;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTextField nisTxt;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
