/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_spk_saw;

import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ferdy
 */
public class Form_Nilai_Sikap extends javax.swing.JFrame {
    int nis = 0;
    int kd_nilaisikap = 0;
    double n1,n2,n3,kd1,kd2,kd3;
    double rata;
    String kelas = "";
    String semester = "";
    String tahunajaran = "";
    String kategori2 = "";
    
private void getDataSiswa() {
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datasiswa");
            datasiswaTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
    }
    
    private void getNilaiSikapSiswa() {
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaisikap");
            nilaisikapTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
    }
    
    private void getCariNilaiSikapSiswa() {
        if (kategori2.equals("") || cari2Txt.getText().equals("")){
            try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaisikap");
            nilaisikapTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
        } else {
            try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaisikap WHERE "+kategori2+" like '%"+cari2Txt.getText()+"%'");
            nilaisikapTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
    }
        }
    }
    

    /**
     * Creates new form Form_Nilai_Sikap
     */
    public Form_Nilai_Sikap() {
        initComponents();
        getNilaiSikapSiswa();
        getDataSiswa();
        nisTxt.setEditable(false);
        namaTxt.setEditable(false);
        tahunajaranTxt.setEditable(false);
        kelakuanTxt.setEditable(false);
        kerajinanTxt.setEditable(false);
        kebersihanTxt.setEditable(false);
        ratarata.setEnabled(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cari1Txt = new javax.swing.JTextField();
        cari1Btn = new javax.swing.JButton();
        refresh1Btn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        datasiswaTbl = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        kategoricari2Cmb = new javax.swing.JComboBox<>();
        cari2Txt = new javax.swing.JTextField();
        cari2Btn = new javax.swing.JButton();
        refresh2Btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nilaisikapTbl = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tahunajaranTxt = new javax.swing.JTextField();
        namaTxt = new javax.swing.JTextField();
        nisTxt = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        kelakuanCmb = new javax.swing.JComboBox<>();
        kerajinanCmb = new javax.swing.JComboBox<>();
        kebersihanCmb = new javax.swing.JComboBox<>();
        kelakuanTxt = new javax.swing.JTextField();
        kerajinanTxt = new javax.swing.JTextField();
        kebersihanTxt = new javax.swing.JTextField();
        prosesBtn = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        ratarata = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        kdnilaisikapTxt = new javax.swing.JTextField();
        simpanBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        bersihkanBtn = new javax.swing.JButton();
        kelasCmb = new javax.swing.JComboBox<>();
        semesterCmb = new javax.swing.JComboBox<>();
        tahunajaranCmb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Nilai Sikap");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Cari NIS atau Nama Siswa");

        cari1Txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cari1Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cari1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        cari1Btn.setText("Cari");
        cari1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari1BtnActionPerformed(evt);
            }
        });

        refresh1Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refresh1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        refresh1Btn.setText("Refresh");
        refresh1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1BtnActionPerformed(evt);
            }
        });

        datasiswaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Tanggal Lahir", "Jenis Kelamin"
            }
        ));
        datasiswaTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datasiswaTblMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(datasiswaTbl);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(cari1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cari1Btn)
                        .addGap(18, 18, 18)
                        .addComponent(refresh1Btn)
                        .addContainerGap(75, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cari1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari1Btn)
                    .addComponent(refresh1Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Data Siswa", jPanel5);

        kategoricari2Cmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kategoricari2Cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Kategori Pencarian-", "NIS", "Nama", "Kelas", "Semester", "Tahun Ajaran" }));
        kategoricari2Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoricari2CmbActionPerformed(evt);
            }
        });

        cari2Txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cari2Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cari2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        cari2Btn.setText("Cari");
        cari2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari2BtnActionPerformed(evt);
            }
        });

        refresh2Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refresh2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        refresh2Btn.setText("Refresh");
        refresh2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh2BtnActionPerformed(evt);
            }
        });

        nilaisikapTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd Nilai Sikap", "NIS", "Nama", "Kelakuan", "Kerajinan", "Kebersihan", "Rata-rata", "Kelas", "Semester", "Tahun Ajaran"
            }
        ));
        nilaisikapTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nilaisikapTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(nilaisikapTbl);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(kategoricari2Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cari2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cari2Btn)
                        .addGap(18, 18, 18)
                        .addComponent(refresh2Btn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategoricari2Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari2Btn)
                    .addComponent(refresh2Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Data Nilai Sikap", jPanel16);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel23.setText("NIS");

        jLabel24.setText("Nama");

        jLabel25.setText("Kelas");

        jLabel26.setText("Semester");

        jLabel27.setText("Tahun Ajaran");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Help.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Sikap"));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setText("Grade");

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel40.setText("Nilai");

        jLabel41.setText("Kelakuan");

        jLabel42.setText("Kerajinan");

        jLabel43.setText("Kebersihan");

        kelakuanCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Sangat Baik (A)", "Baik (B)", "Cukup Baik (C)", "Buruk (D)", "Sangat Buruk (E)" }));
        kelakuanCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelakuanCmbActionPerformed(evt);
            }
        });

        kerajinanCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Sangat Baik (A)", "Baik (B)", "Cukup Baik (C)", "Buruk (D)", "Sangat Buruk (E)" }));
        kerajinanCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kerajinanCmbActionPerformed(evt);
            }
        });

        kebersihanCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Sangat Baik (A)", "Baik (B)", "Cukup Baik (C)", "Buruk (D)", "Sangat Buruk (E)" }));
        kebersihanCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebersihanCmbActionPerformed(evt);
            }
        });

        prosesBtn.setText("Proses");
        prosesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesBtnActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setText("Rata-rata");

        jLabel1.setText("Kode Nilai Sikap");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(kdnilaisikapTxt))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel39))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(18, 18, 18)
                        .addComponent(kebersihanCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                        .addComponent(prosesBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel44))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kerajinanCmb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kelakuanCmb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(kebersihanTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kelakuanTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kerajinanTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ratarata))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kdnilaisikapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(kelakuanCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelakuanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(kerajinanCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kerajinanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(kebersihanCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kebersihanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prosesBtn)
                    .addComponent(jLabel44)
                    .addComponent(ratarata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        simpanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Upload.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        hapusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        bersihkanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clear.png"))); // NOI18N
        bersihkanBtn.setText("Clear");
        bersihkanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanBtnActionPerformed(evt);
            }
        });

        kelasCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "VII-A", "VII-B", "VIII-A", "VIII-B", "IX-A", "IX-B" }));
        kelasCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasCmbActionPerformed(evt);
            }
        });

        semesterCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Ganjil", "Genap" }));
        semesterCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterCmbActionPerformed(evt);
            }
        });

        tahunajaranCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "2018/2019", "2019/2020", "2020/2021", "2021/2022", "2022/2023", "2023/2024", "Input Manual" }));
        tahunajaranCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunajaranCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(namaTxt)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpanBtn)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kelasCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(semesterCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(hapusBtn)
                                .addGap(18, 18, 18)
                                .addComponent(bersihkanBtn))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(tahunajaranCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tahunajaranTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(kelasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(semesterCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tahunajaranCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahunajaranTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanBtn)
                    .addComponent(updateBtn)
                    .addComponent(hapusBtn)
                    .addComponent(bersihkanBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Lihat petunjuk pada tampilan utama aplikasi ini.","Petunjuk",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void kategoricari2CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoricari2CmbActionPerformed
        // TODO add your handling code here:
        if (kategoricari2Cmb.getSelectedIndex()==0){
            kategori2="";}
        else if(kategoricari2Cmb.getSelectedIndex()==1){
            kategori2="Nis_Siswa";}
        else if(kategoricari2Cmb.getSelectedIndex()==2){
            kategori2="Nama";}
        else if(kategoricari2Cmb.getSelectedIndex()==3){
            kategori2="Kelas";}
        else if(kategoricari2Cmb.getSelectedIndex()==4){
            kategori2="Semester";}
        else if(kategoricari2Cmb.getSelectedIndex()==5){
            kategori2="Tahun_Ajaran";}
    }//GEN-LAST:event_kategoricari2CmbActionPerformed

    private void cari2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2BtnActionPerformed
        // TODO add your handling code here:
        if (kategori2.equals("")){
            JOptionPane.showMessageDialog(null, "Pilih kategori pencarian terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaisikap WHERE "+kategori2+" like '%"+cari2Txt.getText()+"%'");
                nilaisikapTbl.setModel(DbUtils.resultSetToTableModel(sql));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_cari2BtnActionPerformed

    private void refresh2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh2BtnActionPerformed
        // TODO add your handling code here:
        cari2Txt.setText("");
        kategoricari2Cmb.setSelectedIndex(0);
        getNilaiSikapSiswa();
    }//GEN-LAST:event_refresh2BtnActionPerformed

    private void nilaisikapTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nilaisikapTblMouseClicked
        // TODO add your handling code here:
        try {
            int row = nilaisikapTbl.getSelectedRow();
            String kliktabel=(nilaisikapTbl.getModel().getValueAt(row,0).toString());
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_nilaisikap WHERE Kd_NilaiSikap='"+kliktabel+"'");

            if (sql.next()) {
                
                kd_nilaisikap = sql.getInt("Kd_NilaiSikap");
                String Skdnilaisikap = Integer.toString(kd_nilaisikap);
                kdnilaisikapTxt.setText(Skdnilaisikap);
                nis = sql.getInt("Nis_Siswa");
                String nisString = Integer.toString(nis);
                nisTxt.setText(nisString);
                String nama = sql.getString("Nama");
                namaTxt.setText(nama);
                rata = sql.getDouble("Ratarata_Sikap");
                ratarata.setText(Double.toString(rata));
                n1 = sql.getDouble("Kelakuan");
                n2 = sql.getDouble("Kerajinan");
                n3 = sql.getDouble("Kebersihan");
                String n1s = Double.toString(n1);
                String n2s = Double.toString(n2);
                String n3s = Double.toString(n3);
                
                if(n1s.equals("4.0")){
                    kelakuanCmb.setSelectedIndex(1);}
               else if(n1s.equals("3.0")){
                    kelakuanCmb.setSelectedIndex(2);}
               else if(n1s.equals("2.0")){
                    kelakuanCmb.setSelectedIndex(3);}
               else if(n1s.equals("1.0")){
                    kelakuanCmb.setSelectedIndex(4);}
               else if(n1s.equals("0.0")){
                    kelakuanCmb.setSelectedIndex(5);}
               kelakuanTxt.setText(n1s);
               
               if(n2s.equals("4.0")){
                    kerajinanCmb.setSelectedIndex(1);}
               else if(n2s.equals("3.0")){
                    kerajinanCmb.setSelectedIndex(2);}
               else if(n2s.equals("2.0")){
                    kerajinanCmb.setSelectedIndex(3);}
               else if(n2s.equals("1.0")){
                    kerajinanCmb.setSelectedIndex(4);}
               else if(n2s.equals("0.0")){
                    kerajinanCmb.setSelectedIndex(5);}
               kerajinanTxt.setText(n2s);
               
               if(n3s.equals("4.0")){
                    kebersihanCmb.setSelectedIndex(1);}
               else if(n3s.equals("3.0")){
                    kebersihanCmb.setSelectedIndex(2);}
               else if(n3s.equals("2.0")){
                    kebersihanCmb.setSelectedIndex(3);}
               else if(n3s.equals("1.0")){
                    kebersihanCmb.setSelectedIndex(4);}
               else if(n3s.equals("0.0")){
                    kebersihanCmb.setSelectedIndex(5);}
               kebersihanTxt.setText(n3s);
            }
            
            String kls = sql.getString("Kelas");
                if(kls.equals("")){
                    kelasCmb.setSelectedIndex(0);}
                else if(kls.equals("VII-A")){
                    kelasCmb.setSelectedIndex(1);}
                else if(kls.equals("VII-B")){
                    kelasCmb.setSelectedIndex(2);}
                else if(kls.equals("VIII-A")){
                    kelasCmb.setSelectedIndex(3);}
                else if(kls.equals("VIII-B")){
                    kelasCmb.setSelectedIndex(4);}
                else if(kls.equals("IX-A")){
                    kelasCmb.setSelectedIndex(5);}
                else if(kls.equals("IX-B")){
                    kelasCmb.setSelectedIndex(6);}


                String smstr = sql.getString("Semester");
                if(smstr.equals("")){
                    semesterCmb.setSelectedIndex(0);}
                else if(smstr.equals("Ganjil")){
                    semesterCmb.setSelectedIndex(1);}
                else if(smstr.equals("Genap")){
                    semesterCmb.setSelectedIndex(2);}

                String thnajaran = sql.getString("Tahun_Ajaran");
                if(thnajaran.equals("")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(0);}
                else if(thnajaran.equals("2018/2019")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(1);}
                else if(thnajaran.equals("2019/2020")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(2);}
                else if(thnajaran.equals("2020/2021")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(3);}
                else if(thnajaran.equals("2021/2022")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(4);}
                else if(thnajaran.equals("2022/2023")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(5);}
                else if(thnajaran.equals("2023/2024")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(6);}
                else{
                    tahunajaranTxt.setEnabled(true);
                    tahunajaranTxt.setText(thnajaran);
                    tahunajaranCmb.setSelectedIndex(7);
                }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        kdnilaisikapTxt.setEnabled(false);
    }//GEN-LAST:event_nilaisikapTblMouseClicked

    private void kelakuanCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelakuanCmbActionPerformed
        // TODO add your handling code here:
        String k1 = "";
        if (kelakuanCmb.getSelectedIndex()==0){ 
            k1="";}
        else if(kelakuanCmb.getSelectedIndex()==1){
            k1="4.0";}
        else if(kelakuanCmb.getSelectedIndex()==2){
            k1="3.0";}
        else if(kelakuanCmb.getSelectedIndex()==3){
            k1="2.0";}
        else if(kelakuanCmb.getSelectedIndex()==4){
            k1="1.0";}
        else if(kelakuanCmb.getSelectedIndex()==5){
            k1="0.0";}
        kelakuanTxt.setText(k1);
    }//GEN-LAST:event_kelakuanCmbActionPerformed

    private void kerajinanCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kerajinanCmbActionPerformed
        // TODO add your handling code here:
        String k2 = "";
        if (kerajinanCmb.getSelectedIndex()==0){ 
            k2="";}
        else if(kerajinanCmb.getSelectedIndex()==1){
            k2="4.0";}
        else if(kerajinanCmb.getSelectedIndex()==2){
            k2="3.0";}
        else if(kerajinanCmb.getSelectedIndex()==3){
            k2="2.0";}
        else if(kerajinanCmb.getSelectedIndex()==4){
            k2="1.0";}
        else if(kerajinanCmb.getSelectedIndex()==5){
            k2="0.0";}
        kerajinanTxt.setText(k2);
    }//GEN-LAST:event_kerajinanCmbActionPerformed

    private void kebersihanCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebersihanCmbActionPerformed
        // TODO add your handling code here:
        String k3 = "";
        if (kebersihanCmb.getSelectedIndex()==0){ 
            k3="";}
        else if(kebersihanCmb.getSelectedIndex()==1){
            k3="4.0";}
        else if(kebersihanCmb.getSelectedIndex()==2){
            k3="3.0";}
        else if(kebersihanCmb.getSelectedIndex()==3){
            k3="2.0";}
        else if(kebersihanCmb.getSelectedIndex()==4){
            k3="1.0";}
        else if(kebersihanCmb.getSelectedIndex()==5){
            k3="0.0";}
        kebersihanTxt.setText(k3);
    }//GEN-LAST:event_kebersihanCmbActionPerformed

    private void prosesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesBtnActionPerformed
        // TODO add your handling code here:
        if(kelakuanTxt.getText().equals("") || kerajinanTxt.getText().equals("") || kebersihanTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Silakan diinput nilai sikapnya.","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }else{
            n1 = Double.parseDouble(kelakuanTxt.getText());
            n2 = Double.parseDouble(kerajinanTxt.getText());
            n3 = Double.parseDouble(kebersihanTxt.getText());
            double jumlah = n1+n2+n3;
            rata = jumlah/3;
            ratarata.setText(Double.toString(rata));
        }
    }//GEN-LAST:event_prosesBtnActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        String nisnya = null;
        String namanya = null;
        String kelasnya = null;
        String semesternya = null;
        
        if (kelasCmb.getSelectedIndex()==0){
            kelas="";}
        else if(kelasCmb.getSelectedIndex()==1){
            kelas="VII-A";}
        else if(kelasCmb.getSelectedIndex()==2){
            kelas="VII-B";}
        else if(kelasCmb.getSelectedIndex()==3){
            kelas="VIII-A";}
        else if(kelasCmb.getSelectedIndex()==4){
            kelas="VIII-B";}
        else if(kelasCmb.getSelectedIndex()==5){
            kelas="IX-A";}
        else if(kelasCmb.getSelectedIndex()==6){
            kelas="IX-B";}

        if (semesterCmb.getSelectedIndex()==0){
            semester="";}
        else if(semesterCmb.getSelectedIndex()==1){
            semester="Ganjil";}
        else if(semesterCmb.getSelectedIndex()==2){
            semester="Genap";}

        if (tahunajaranCmb.getSelectedIndex()==0){
            tahunajaran="";}
        else if(tahunajaranCmb.getSelectedIndex()==1){
            tahunajaran="2018/2019";}
        else if(tahunajaranCmb.getSelectedIndex()==2){
            tahunajaran="2019/2020";}
        else if(tahunajaranCmb.getSelectedIndex()==3){
            tahunajaran="2020/2021";}
        else if(tahunajaranCmb.getSelectedIndex()==4){
            tahunajaran="2021/2022";}
        else if(tahunajaranCmb.getSelectedIndex()==5){
            tahunajaran="2022/2023";}
        else if(tahunajaranCmb.getSelectedIndex()==6){
            tahunajaran="2023/2024";}
        else if(tahunajaranCmb.getSelectedIndex()==7){
            tahunajaran=tahunajaranTxt.getText();}
        
        if (kdnilaisikapTxt.getText().equals("") ||nisTxt.getText().equals("") || namaTxt.getText().equals("") || kelas.equals("") || semester.equals("") || tahunajaran.equals("")
                || kelakuanTxt.getText().equals("") || kerajinanTxt.getText().equals("") || kebersihanTxt.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }else {
            kd1 = Double.parseDouble(kelakuanTxt.getText());
            kd2 = Double.parseDouble(kerajinanTxt.getText());
            kd3 = Double.parseDouble(kebersihanTxt.getText());
            try {
                java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet sqll = stm.executeQuery("SELECT Nis_Siswa, Nama, Kelas, Semester FROM tb_nilaisikap WHERE Nis_Siswa='"+nisTxt.getText()+"' AND Kelas='"+kelas+"' AND Semester='"+semester+"'");        
                if (sqll.next()) {
                    nis = sqll.getInt("Nis_siswa");
                    nisnya = Integer.toString(nis);
                    namanya = sqll.getString("Nama");
                    kelasnya = sqll.getString("Kelas");
                    semesternya = sqll.getString("Semester");
                }else {}
                if (nisTxt.getText().equals(nisnya) && kelas.equals(kelasnya) && semester.equals(semesternya)){
                    JOptionPane.showMessageDialog(null, "Nilai Sikap "+namaTxt.getText()+" kelas "+kelas+" pada semester "+semester+" sudah ada!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);    
                }else {         
                    String sql = "INSERT INTO tb_nilaisikap VALUES('"+kdnilaisikapTxt.getText()+"','"+nisTxt.getText()+"','"+namaTxt.getText()+"','"+kd1+"','"+kd2+"','"+kd3+"','"+rata+"',"
                            + "'"+kelas+"','"+semester+"','"+tahunajaran+"')";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Nilai Sikap siswa berhasil disimpan!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                }
            }catch(SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Nilai Sikap siswa gagal disimpan!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            }
            getNilaiSikapSiswa();
            kd_nilaisikap = 0;
            nisTxt.setText("");
            namaTxt.setText("");
            kelasCmb.setSelectedIndex(0);
            semesterCmb.setSelectedIndex(0);
            tahunajaranCmb.setSelectedIndex(0);
            tahunajaranTxt.setText("");
            kdnilaisikapTxt.setText("");
            kelakuanCmb.setSelectedIndex(0);
            kerajinanCmb.setSelectedIndex(0);
            kebersihanCmb.setSelectedIndex(0);
            kelakuanTxt.setText("");
            kerajinanTxt.setText("");
            kebersihanTxt.setText("");
            ratarata.setText("");
        }
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
         String kelas = null;
        if (kelasCmb.getSelectedIndex()==0){
            kelas="";}
        else if(kelasCmb.getSelectedIndex()==1){
            kelas="VII-A";}
        else if(kelasCmb.getSelectedIndex()==2){
            kelas="VII-B";}
        else if(kelasCmb.getSelectedIndex()==3){
            kelas="VIII-A";}
        else if(kelasCmb.getSelectedIndex()==4){
            kelas="VIII-B";}
        else if(kelasCmb.getSelectedIndex()==5){
            kelas="IX-A";}
        else if(kelasCmb.getSelectedIndex()==6){
            kelas="IX-B";}

        String semester = null;
        if (semesterCmb.getSelectedIndex()==0){
            semester="";}
        else if(semesterCmb.getSelectedIndex()==1){
            semester="Ganjil";}
        else if(semesterCmb.getSelectedIndex()==2){
            semester="Genap";}

        String tahunajaran = null;
        if (tahunajaranCmb.getSelectedIndex()==0){
            tahunajaran="";}
        else if(tahunajaranCmb.getSelectedIndex()==1){
            tahunajaran="2018/2019";}
        else if(tahunajaranCmb.getSelectedIndex()==2){
            tahunajaran="2019/2020";}
        else if(tahunajaranCmb.getSelectedIndex()==3){
            tahunajaran="2020/2021";}
        else if(tahunajaranCmb.getSelectedIndex()==4){
            tahunajaran="2021/2022";}
        else if(tahunajaranCmb.getSelectedIndex()==5){
            tahunajaran="2022/2023";}
        else if(tahunajaranCmb.getSelectedIndex()==6){
            tahunajaran="2023/2024";}
        else if(tahunajaranCmb.getSelectedIndex()==7){
            tahunajaran=tahunajaranTxt.getText();}
        
        if (kd_nilaisikap == 0){
            JOptionPane.showMessageDialog(null, "Pilih nilai Sikap siswa yang ingin diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }else{
            if (nisTxt.getText().equals("") || namaTxt.getText().equals("") || kelas.equals("") || semester.equals("") || tahunajaran.equals("")
                    || kelakuanTxt.getText().equals("") || kerajinanTxt.getText().equals("") || kebersihanTxt.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            }else {
                kd1 = Double.parseDouble(kelakuanTxt.getText());
                kd2 = Double.parseDouble(kerajinanTxt.getText());
                kd3 = Double.parseDouble(kebersihanTxt.getText());
                try {
                    java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                    String sql = "UPDATE tb_nilaisikap SET Nis_Siswa='"+nisTxt.getText()+"', Nama='"+namaTxt.getText()+"', Kelakuan='"+kd1+"', Kerajinan='"+kd2+"', Kebersihan='"+kd3+"',Ratarata_Sikap ='"+rata+"', "
                            + "Kelas='"+kelas+"', Semester='"+semester+"', Tahun_Ajaran='"+tahunajaran+"' WHERE Kd_NilaiSikap='"+kd_nilaisikap+"'";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Nilai Sikap siswa berhasil diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                }catch (SQLException | HeadlessException e){
                    JOptionPane.showMessageDialog(null, "Nilai Sikap siswa gagal diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        getNilaiSikapSiswa();
        kd_nilaisikap = 0;
        kdnilaisikapTxt.setEnabled(true);
        nisTxt.setText("");
        namaTxt.setText("");
        kelasCmb.setSelectedIndex(0);
        semesterCmb.setSelectedIndex(0);
        tahunajaranCmb.setSelectedIndex(0);
        tahunajaranTxt.setText("");
        kdnilaisikapTxt.setText("");
        kelakuanCmb.setSelectedIndex(0);
        kerajinanCmb.setSelectedIndex(0);
        kebersihanCmb.setSelectedIndex(0);
        kelakuanTxt.setText("");
        kerajinanTxt.setText("");
        kebersihanTxt.setText("");
        ratarata.setText("");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        // TODO add your handling code here:
        if (kd_nilaisikap == 0){
            JOptionPane.showMessageDialog(null, "Pilih Nilai Sikap siswa yang ingin dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            Object[] options = {"Iya", "Tidak"};
            int van = JOptionPane.showOptionDialog(this, "Anda yakin ingin menghapus data Nilai Sikap "+namaTxt.getText()+"?",
            "Konfirmasi", JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            if(van== 0){
                try {
                    java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                    String sql = "DELETE FROM tb_nilaisikap WHERE Kd_NilaiSikap='"+kd_nilaisikap+"'";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Nilai Sikap siswa berhasil dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException | HeadlessException e) {
                    JOptionPane.showMessageDialog(null, "Nilai Sikap siswa gagal dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                }
                getNilaiSikapSiswa();}
            else if(van== 1){
            }
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void bersihkanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanBtnActionPerformed
        // TODO add your handling code here:
        kdnilaisikapTxt.setEnabled(true);
        kd_nilaisikap = 0;
        nisTxt.setText("");
        namaTxt.setText("");
        kelasCmb.setSelectedIndex(0);
        semesterCmb.setSelectedIndex(0);
        tahunajaranCmb.setSelectedIndex(0);
        tahunajaranTxt.setText("");
        kdnilaisikapTxt.setText("");
        kelakuanCmb.setSelectedIndex(0);
        kerajinanCmb.setSelectedIndex(0);
        kebersihanCmb.setSelectedIndex(0);
        kelakuanTxt.setText("");
        kerajinanTxt.setText("");
        kebersihanTxt.setText("");
        ratarata.setText("");
    }//GEN-LAST:event_bersihkanBtnActionPerformed

    private void cari1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari1BtnActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datasiswa WHERE Nis_Siswa like '%"+cari1Txt.getText()+"%' or Nama like '%"+cari1Txt.getText()+"%'");
            datasiswaTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cari1BtnActionPerformed

    private void refresh1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1BtnActionPerformed
        // TODO add your handling code here:
        getDataSiswa();
        cari1Txt.setText("");
    }//GEN-LAST:event_refresh1BtnActionPerformed

    private void datasiswaTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datasiswaTblMouseClicked
        // TODO add your handling code here:
        try {
            int row = datasiswaTbl.getSelectedRow();
            String kliktabel=(datasiswaTbl.getModel().getValueAt(row,0).toString());
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT Nis_Siswa, Nama FROM tb_datasiswa WHERE Nis_siswa='"+kliktabel+"'");

            if (sql.next()) {
                nis = sql.getInt("Nis_siswa");
                String nisString = Integer.toString(nis);
                nisTxt.setText(nisString);
                String nama = sql.getString("Nama");
                namaTxt.setText(nama);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_datasiswaTblMouseClicked

    private void semesterCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterCmbActionPerformed
        // TODO add your handling code here:
        if (semesterCmb.getSelectedIndex()==0){
            semester="";}
        else if(semesterCmb.getSelectedIndex()==1){
            semester="Ganjil";}
        else if(semesterCmb.getSelectedIndex()==2){
            semester="Genap";}
    }//GEN-LAST:event_semesterCmbActionPerformed

    private void tahunajaranCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunajaranCmbActionPerformed
        // TODO add your handling code here:\
        if (tahunajaranCmb.getSelectedIndex()==0){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==1){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==2){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==3){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==4){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==5){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==6){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==7){
            tahunajaranTxt.setEnabled(true);}
    }//GEN-LAST:event_tahunajaranCmbActionPerformed

    private void kelasCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasCmbActionPerformed
        // TODO add your handling code here:
        if (kelasCmb.getSelectedIndex()==0){
            kelas="";}
        else if(kelasCmb.getSelectedIndex()==1){
            kelas="VII-A";}
        else if(kelasCmb.getSelectedIndex()==2){
            kelas="VII-B";}
        else if(kelasCmb.getSelectedIndex()==3){
            kelas="VIII-A";}
        else if(kelasCmb.getSelectedIndex()==4){
            kelas="VIII-B";}
        else if(kelasCmb.getSelectedIndex()==5){
            kelas="IX-A";}
        else if(kelasCmb.getSelectedIndex()==6){
            kelas="IX-B";}
    }//GEN-LAST:event_kelasCmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_Sikap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_Sikap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_Sikap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_Sikap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Nilai_Sikap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bersihkanBtn;
    private javax.swing.JButton cari1Btn;
    private javax.swing.JTextField cari1Txt;
    private javax.swing.JButton cari2Btn;
    private javax.swing.JTextField cari2Txt;
    private javax.swing.JTable datasiswaTbl;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JComboBox<String> kategoricari2Cmb;
    private javax.swing.JTextField kdnilaisikapTxt;
    private javax.swing.JComboBox<String> kebersihanCmb;
    private javax.swing.JTextField kebersihanTxt;
    private javax.swing.JComboBox<String> kelakuanCmb;
    private javax.swing.JTextField kelakuanTxt;
    private javax.swing.JComboBox<String> kelasCmb;
    private javax.swing.JComboBox<String> kerajinanCmb;
    private javax.swing.JTextField kerajinanTxt;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTable nilaisikapTbl;
    private javax.swing.JTextField nisTxt;
    private javax.swing.JButton prosesBtn;
    private javax.swing.JTextField ratarata;
    private javax.swing.JButton refresh1Btn;
    private javax.swing.JButton refresh2Btn;
    private javax.swing.JComboBox<String> semesterCmb;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JComboBox<String> tahunajaranCmb;
    private javax.swing.JTextField tahunajaranTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
