/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_spk_saw;

import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ferdy
 */
public class Form_Nilai_Siswa extends javax.swing.JFrame {

    double n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, n11, n12, n13, n14, n15, n16;
    double ratarata = 0.0;
    int nis = 0;
    int kd_nilai = 0;
    String kelas = "";
    String semester = "";
    String tahunajaran="";
    String kategori = "";
    
    private void getDataSiswa() {
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datasiswa");
            datasiswaTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
    }
    
    private void getNilaiSiswa() {
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datanilai");
            datanilaiTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
    }
    
    private void getCariNilaiSiswa() {
        if (kategori.equals("") || cari2Txt.equals("")){
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datanilai");
            datanilaiTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        } else {
            try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datanilai WHERE "+kategori+" like '%"+cari2Txt.getText()+"%'");
            datanilaiTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e){
    }
        }
    }

    /**
     * Creates new form Form_Nilai_Siswa
     */
    public Form_Nilai_Siswa() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setExtendedState(MAXIMIZED_BOTH);
        getDataSiswa();
        getNilaiSiswa();
        nisTxt.setEditable(false);
        namaTxt.setEditable(false);
        ratarataTxt.setEditable(false);
        tahunajaranTxt.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nisTxt = new javax.swing.JTextField();
        namaTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ratarataTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        semesterCmb = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        tahunajaranCmb = new javax.swing.JComboBox<>();
        tahunajaranTxt = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        kelasCmb = new javax.swing.JComboBox<>();
        simpanBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        bersihkanBtn = new javax.swing.JButton();
        prosesBtn = new javax.swing.JButton();
        infoBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        n6Txt = new javax.swing.JTextField();
        n1Txt = new javax.swing.JTextField();
        n2Txt = new javax.swing.JTextField();
        n3Txt = new javax.swing.JTextField();
        n4Txt = new javax.swing.JTextField();
        n5Txt = new javax.swing.JTextField();
        n7Txt = new javax.swing.JTextField();
        n8Txt = new javax.swing.JTextField();
        n12Txt = new javax.swing.JTextField();
        n9Txt = new javax.swing.JTextField();
        n10Txt = new javax.swing.JTextField();
        n11Txt = new javax.swing.JTextField();
        n13Txt = new javax.swing.JTextField();
        n14Txt = new javax.swing.JTextField();
        n15Txt = new javax.swing.JTextField();
        n16Txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kdnilaiTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cari1Txt = new javax.swing.JTextField();
        cari1Btn = new javax.swing.JButton();
        refresh1Btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        datasiswaTbl = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        kategoriCmb = new javax.swing.JComboBox<>();
        cari2Txt = new javax.swing.JTextField();
        cari2Btn = new javax.swing.JButton();
        refresh2Btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        datanilaiTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Nilai Akademik Siswa");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/computer.png")).getImage());
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nilai Akademik Siswa"));

        jLabel4.setText("Qurdis");

        jLabel5.setText("Aqidah");

        jLabel6.setText("Fiqih");

        jLabel7.setText("SKI");

        jLabel8.setText("PKN");

        jLabel9.setText("B. Indonesia");

        jLabel10.setText("MTK");

        jLabel11.setText("IPA");

        jLabel12.setText("IPS");

        jLabel13.setText("NIS");

        jLabel14.setText("Nama Siswa");

        jLabel3.setText("Seni Budaya");

        jLabel15.setText("Penjas");

        jLabel16.setText("TIK");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Nilai Rata-Rata");

        jLabel31.setText("Semester");

        semesterCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "Ganjil", "Genap" }));
        semesterCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterCmbActionPerformed(evt);
            }
        });

        jLabel32.setText("Tahun Ajaran");

        tahunajaranCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "2018/2019", "2019/2020", "2020/2021", "2021/2022", "2022/2023", "2023/2024", "Input Manual" }));
        tahunajaranCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunajaranCmbActionPerformed(evt);
            }
        });

        jLabel30.setText("Kelas");

        kelasCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih-", "VII-A", "VII-B", "VIII-A", "VIII-B", "IX-A", "IX-B" }));
        kelasCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasCmbActionPerformed(evt);
            }
        });

        simpanBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        simpanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Upload.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        hapusBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hapusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        bersihkanBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bersihkanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clear.png"))); // NOI18N
        bersihkanBtn.setText("Clear");
        bersihkanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanBtnActionPerformed(evt);
            }
        });

        prosesBtn.setText("Proses");
        prosesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesBtnActionPerformed(evt);
            }
        });

        infoBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Help.png"))); // NOI18N
        infoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoBtnActionPerformed(evt);
            }
        });

        jLabel18.setText("B. Arab");

        jLabel19.setText("B. Inggris");

        jLabel20.setText("BTQ");

        jLabel21.setText("Prakarya");

        n1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1TxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Kode Nilai");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel9))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(n8Txt)
                                    .addComponent(n7Txt)
                                    .addComponent(n6Txt)
                                    .addComponent(n5Txt)
                                    .addComponent(n4Txt)
                                    .addComponent(n1Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(n2Txt)
                                    .addComponent(n3Txt))
                                .addGap(112, 112, 112)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(n16Txt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n15Txt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n14Txt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n13Txt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n11Txt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n10Txt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n9Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(n12Txt)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel2))
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kdnilaiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(64, 64, 64)
                                        .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(infoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(prosesBtn)
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel17)
                                        .addGap(4, 4, 4)
                                        .addComponent(ratarataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(18, 18, 18)
                                        .addComponent(tahunajaranCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tahunajaranTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(simpanBtn)
                                        .addGap(6, 6, 6)
                                        .addComponent(updateBtn)
                                        .addGap(6, 6, 6)
                                        .addComponent(hapusBtn)
                                        .addGap(6, 6, 6)
                                        .addComponent(bersihkanBtn))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel30)
                                            .addGap(58, 58, 58)
                                            .addComponent(kelasCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel31)
                                            .addGap(38, 38, 38)
                                            .addComponent(semesterCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel13))
                            .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoBtn))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel14))
                            .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kdnilaiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(n1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(n9Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(n2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(n10Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(n3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(n11Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(n4Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(n12Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(n5Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n13Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n15Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n6Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel16)
                            .addComponent(n14Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(n7Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(n8Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(n16Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prosesBtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ratarataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel30))
                    .addComponent(kelasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel31))
                    .addComponent(semesterCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel32))
                    .addComponent(tahunajaranCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahunajaranTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpanBtn)
                    .addComponent(updateBtn)
                    .addComponent(hapusBtn)
                    .addComponent(bersihkanBtn)))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Cari NIS atau Nama Siswa");

        cari1Txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cari1Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cari1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        cari1Btn.setText("Cari");
        cari1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari1BtnActionPerformed(evt);
            }
        });

        refresh1Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refresh1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        refresh1Btn.setText("Refresh");
        refresh1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1BtnActionPerformed(evt);
            }
        });

        datasiswaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Tanggal Lahir", "Jenis Kelamin"
            }
        ));
        datasiswaTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datasiswaTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(datasiswaTbl);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cari1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cari1Btn)
                        .addGap(18, 18, 18)
                        .addComponent(refresh1Btn)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cari1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari1Btn)
                    .addComponent(refresh1Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Siswa", jPanel3);

        kategoriCmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kategoriCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Kategori Pencarian-", "NIS", "Nama Siswa", "Kelas", "Semester", "Tahun Ajaran" }));
        kategoriCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriCmbActionPerformed(evt);
            }
        });

        cari2Txt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cari2Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cari2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        cari2Btn.setText("Cari");
        cari2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari2BtnActionPerformed(evt);
            }
        });

        refresh2Btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refresh2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        refresh2Btn.setText("Refresh");
        refresh2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh2BtnActionPerformed(evt);
            }
        });

        datanilaiTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd_Nilai", "NIS", "Nama", "Qurdis", "Aqidah", "Fiqih", "SKI", "PKN", "B. Indonesia", "B. Arab", "B. Inggris", "MTK", "IPA", "IPS", "Seni Budaya", "Penjas", "TIK", "BTQ", "Prakarya", "Nilai Rata-Rata", "Kelas", "Semester", "Tahun Ajaran"
            }
        ));
        datanilaiTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datanilaiTblMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(datanilaiTbl);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1678, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel6);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kategoriCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cari2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cari2Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(refresh2Btn)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategoriCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari2Btn)
                    .addComponent(refresh2Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );

        jTabbedPane1.addTab("Data Nilai Akademik Siswa", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refresh2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh2BtnActionPerformed
        // TODO add your handling code here:
        cari2Txt.setText("");
        kategoriCmb.setSelectedIndex(0);
        getNilaiSiswa();
    }//GEN-LAST:event_refresh2BtnActionPerformed

    private void cari2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari2BtnActionPerformed
        // TODO add your handling code here:
        if (kategori.equals("")){
            JOptionPane.showMessageDialog(null, "Pilih kategori pencarian terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datanilai WHERE "+kategori+" like '%"+cari2Txt.getText()+"%'");
                datanilaiTbl.setModel(DbUtils.resultSetToTableModel(sql));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_cari2BtnActionPerformed

    private void kategoriCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriCmbActionPerformed
        // TODO add your handling code here:
        if (kategoriCmb.getSelectedIndex()==0){
            kategori="";}
        else if(kategoriCmb.getSelectedIndex()==1){
            kategori="Nis_siswa";}
        else if(kategoriCmb.getSelectedIndex()==2){
            kategori="Nama";}
        else if(kategoriCmb.getSelectedIndex()==3){
            kategori="Kelas";}
        else if(kategoriCmb.getSelectedIndex()==4){
            kategori="Semester";}
        else if(kategoriCmb.getSelectedIndex()==5){
            kategori="Tahun_Ajaran";}
    }//GEN-LAST:event_kategoriCmbActionPerformed

    private void infoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Lihat petunjuk pada tampilan utama aplikasi ini.","Petunjuk",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_infoBtnActionPerformed

    private void prosesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesBtnActionPerformed
        // TODO add your handling code here:
        try{
        n1 = Double.parseDouble(n1Txt.getText());
        n2 = Double.parseDouble(n2Txt.getText());
        n3 = Double.parseDouble(n3Txt.getText());
        n4 = Double.parseDouble(n4Txt.getText());
        n5 = Double.parseDouble(n5Txt.getText());
        n6 = Double.parseDouble(n6Txt.getText());
        n7 = Double.parseDouble(n7Txt.getText());
        n8 = Double.parseDouble(n8Txt.getText());
        n9 = Double.parseDouble(n9Txt.getText());
        n10 = Double.parseDouble(n10Txt.getText());
        n11 = Double.parseDouble(n11Txt.getText());
        n12 = Double.parseDouble(n12Txt.getText());
        n13 = Double.parseDouble(n13Txt.getText());
        n14 = Double.parseDouble(n14Txt.getText());
        n15 = Double.parseDouble(n15Txt.getText());
        n16 = Double.parseDouble(n16Txt.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Inputan Nilai Salah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        if(n1>100 || n2>100 || n3>100 || n4>100 || n5>100 || n6>100 || n7>100 || n8>100 || n9>100 
                || n10>100 || n11>100 || n12>100 || n13>100 || n14>100 || n15>100 || n16>100){
            JOptionPane.showMessageDialog(null, "Nilai melebihi 100!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else{
            double jumlah = n1+n2+n3+n4+n5+n6+n7+n8+n9+n10+n11+n12+n13+n14+n15+n16;
            ratarata = jumlah/16;
            ratarataTxt.setText(Double.toString(ratarata));
        }
        
    }//GEN-LAST:event_prosesBtnActionPerformed

    private void bersihkanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanBtnActionPerformed
        // TODO add your handling code here:
        kd_nilai = 0;
        nisTxt.setText("");
        namaTxt.setText("");
        n1Txt.setText("");
        n2Txt.setText("");
        n3Txt.setText("");
        n4Txt.setText("");
        n5Txt.setText("");
        n6Txt.setText("");
        n7Txt.setText("");
        n8Txt.setText("");
        n9Txt.setText("");
        n10Txt.setText("");
        n11Txt.setText("");
        n12Txt.setText("");
        n13Txt.setText("");
        n14Txt.setText("");
        n15Txt.setText("");
        n16Txt.setText("");
        ratarataTxt.setText("");
        kelasCmb.setSelectedIndex(0);
        semesterCmb.setSelectedIndex(0);
        tahunajaranCmb.setSelectedIndex(0);
        tahunajaranTxt.setText("");
        kdnilaiTxt.setText("");
        kdnilaiTxt.setEnabled(true);
    }//GEN-LAST:event_bersihkanBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        // TODO add your handling code here:
        if (kd_nilai == 0){
            JOptionPane.showMessageDialog(null, "Pilih nilai akademik siswa yang ingin dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            Object[] options = {"Iya", "Tidak"};
            int van = JOptionPane.showOptionDialog(this, "Anda yakin ingin menghapus data nilai akademik "+namaTxt.getText()+"?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            if(van== 0){
                try {
                    String sql = "DELETE FROM tb_datanilai WHERE Kd_Nilai='"+kd_nilai+"'";
                    java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Nilai akademik siswa berhasil dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException | HeadlessException e) {
                    JOptionPane.showMessageDialog(null, "Nilai akademik siswa gagal dihapus!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                }
                getCariNilaiSiswa();}
            else if(van== 1){
            }
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String kelas = null;
        if (kelasCmb.getSelectedIndex()==0){
            kelas="";}
        else if(kelasCmb.getSelectedIndex()==1){
            kelas="VII-A";}
        else if(kelasCmb.getSelectedIndex()==2){
            kelas="VII-B";}
        else if(kelasCmb.getSelectedIndex()==3){
            kelas="VIII-A";}
        else if(kelasCmb.getSelectedIndex()==4){
            kelas="VIII-B";}
        else if(kelasCmb.getSelectedIndex()==5){
            kelas="IX-A";}
        else if(kelasCmb.getSelectedIndex()==6){
            kelas="IX-B";}

        String semester = null;
        if (semesterCmb.getSelectedIndex()==0){
            semester="";}
        else if(semesterCmb.getSelectedIndex()==1){
            semester="Ganjil";}
        else if(semesterCmb.getSelectedIndex()==2){
            semester="Genap";}

        String tahunajaran = null;
        if (tahunajaranCmb.getSelectedIndex()==0){
            tahunajaran="";}
        else if(tahunajaranCmb.getSelectedIndex()==1){
            tahunajaran="2018/2019";}
        else if(tahunajaranCmb.getSelectedIndex()==2){
            tahunajaran="2019/2020";}
        else if(tahunajaranCmb.getSelectedIndex()==3){
            tahunajaran="2020/2021";}
        else if(tahunajaranCmb.getSelectedIndex()==4){
            tahunajaran="2021/2022";}
        else if(tahunajaranCmb.getSelectedIndex()==5){
            tahunajaran="2022/2023";}
        else if(tahunajaranCmb.getSelectedIndex()==6){
            tahunajaran="2023/2024";}
        else if(tahunajaranCmb.getSelectedIndex()==7){
            tahunajaran=tahunajaranTxt.getText();}
        
        
        if (kd_nilai == 0){
            JOptionPane.showMessageDialog(null, "Pilih nilai akademik siswa yang ingin diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (nisTxt.getText().equals("") || namaTxt.getText().equals("") || n1Txt.getText().equals("") || n2Txt.getText().equals("") || n3Txt.getText().equals("") || n4Txt.getText().equals("") || n5Txt.getText().equals("") || n6Txt.getText().equals("") ||
                n7Txt.getText().equals("") || n8Txt.getText().equals("") || n9Txt.getText().equals("") || n10Txt.getText().equals("") || n11Txt.getText().equals("") || n12Txt.getText().equals("") || n13Txt.getText().equals("") || n14Txt.getText().equals("") ||
                n15Txt.getText().equals("") || n16Txt.getText().equals("") ||  ratarataTxt.getText().equals("") || kelas.equals("") || semester.equals("") || tahunajaran.equals("")) {
                JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {
                    java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                    String sql = "UPDATE tb_datanilai SET Nis_Siswa='"+nisTxt.getText()+"', Nama='"+namaTxt.getText()+"', Qurdis='"+n1Txt.getText()+"', Aqidah='"+n2Txt.getText()+"', Fiqih='"+n3Txt.getText()+"', SKI='"+n4Txt.getText()+"', PKN='"+n5Txt.getText()+"', "
                            + "B_Indonesia='"+n6Txt.getText()+"', B_Arab='"+n7Txt.getText()+"', B_Inggris='"+n8Txt.getText()+"', MTK='"+n9Txt.getText()+"', IPA='"+n10Txt.getText()+"', IPS='"+n11Txt.getText()+"', Seni_Budaya='"+n12Txt.getText()+"', Penjas='"+n13Txt.getText()+"', "
                            + "TIK='"+n14Txt.getText()+"', BTQ='"+n15Txt.getText()+"', Prakarya='"+n16Txt.getText()+"', Nilai_Ratarata='"+ratarataTxt.getText()+"', Kelas='"+kelas+"', Semester='"+semester+"', Tahun_Ajaran='"+tahunajaran+"' WHERE Kd_Nilai ='"+kd_nilai+"'";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Nilai akademik siswa berhasil diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException | HeadlessException e){
                    JOptionPane.showMessageDialog(null, "Nilai akademik siswa gagal diubah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            getCariNilaiSiswa();
            kdnilaiTxt.setEnabled(true);
            kd_nilai = 0;
        nisTxt.setText("");
        namaTxt.setText("");
        n1Txt.setText("");
        n2Txt.setText("");
        n3Txt.setText("");
        n4Txt.setText("");
        n5Txt.setText("");
        n6Txt.setText("");
        n7Txt.setText("");
        n8Txt.setText("");
        n9Txt.setText("");
        n10Txt.setText("");
        n11Txt.setText("");
        n12Txt.setText("");
        n13Txt.setText("");
        n14Txt.setText("");
        n15Txt.setText("");
        n16Txt.setText("");
        ratarataTxt.setText("");
        kelasCmb.setSelectedIndex(0);
        semesterCmb.setSelectedIndex(0);
        tahunajaranCmb.setSelectedIndex(0);
        tahunajaranTxt.setText("");
        kdnilaiTxt.setText("");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        // TODO add your handling code here:
        String nisnya = null;
        String namanya = null;
        String kelasnya = null;
        String semesternya = null;

        if (kelasCmb.getSelectedIndex()==0){
            kelas="";}
        else if(kelasCmb.getSelectedIndex()==1){
            kelas="VII-A";}
        else if(kelasCmb.getSelectedIndex()==2){
            kelas="VII-B";}
        else if(kelasCmb.getSelectedIndex()==3){
            kelas="VIII-A";}
        else if(kelasCmb.getSelectedIndex()==4){
            kelas="VIII-B";}
        else if(kelasCmb.getSelectedIndex()==5){
            kelas="IX-A";}
        else if(kelasCmb.getSelectedIndex()==6){
            kelas="IX-B";}

        if (semesterCmb.getSelectedIndex()==0){
            semester="";}
        else if(semesterCmb.getSelectedIndex()==1){
            semester="Ganjil";}
        else if(semesterCmb.getSelectedIndex()==2){
            semester="Genap";}

        if (tahunajaranCmb.getSelectedIndex()==0){
            tahunajaran="";}
        else if(tahunajaranCmb.getSelectedIndex()==1){
            tahunajaran="2018/2019";}
        else if(tahunajaranCmb.getSelectedIndex()==2){
            tahunajaran="2019/2020";}
        else if(tahunajaranCmb.getSelectedIndex()==3){
            tahunajaran="2020/2021";}
        else if(tahunajaranCmb.getSelectedIndex()==4){
            tahunajaran="2021/2022";}
        else if(tahunajaranCmb.getSelectedIndex()==5){
            tahunajaran="2022/2023";}
        else if(tahunajaranCmb.getSelectedIndex()==6){
            tahunajaran="2023/2024";}
        else if(tahunajaranCmb.getSelectedIndex()==7){
            tahunajaran=tahunajaranTxt.getText();}

        if (kdnilaiTxt.getText().equals("") ||nisTxt.getText().equals("") || namaTxt.getText().equals("") || n1Txt.getText().equals("") || n2Txt.getText().equals("") || n3Txt.getText().equals("") || n4Txt.getText().equals("") || n5Txt.getText().equals("") || n6Txt.getText().equals("") ||
                n7Txt.getText().equals("") || n8Txt.getText().equals("") || n9Txt.getText().equals("") || n10Txt.getText().equals("") || n11Txt.getText().equals("") || n12Txt.getText().equals("") || n13Txt.getText().equals("") || n14Txt.getText().equals("") ||
                n15Txt.getText().equals("") || n16Txt.getText().equals("") ||  ratarataTxt.getText().equals("") || kelas.equals("") || semester.equals("") || tahunajaran.equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon lengkapi data terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet sqll = stm.executeQuery("SELECT Nis_Siswa, Nama, Kelas, Semester FROM tb_datanilai WHERE Nis_Siswa='"+nisTxt.getText()+"' AND Kelas='"+kelas+"' AND Semester='"+semester+"'");
                if (sqll.next()) {
                    nis = sqll.getInt("Nis_Siswa");
                    nisnya = Integer.toString(nis);
                    namanya = sqll.getString("Nama");
                    kelasnya = sqll.getString("Kelas");
                    semesternya = sqll.getString("Semester");
                } else {}
                if (nisTxt.getText().equals(nisnya) && kelas.equals(kelasnya) && semester.equals(semesternya)){
                    JOptionPane.showMessageDialog(null, "Nilai akademik "+namaTxt.getText()+" kelas "+kelas+" pada semester "+semester+" sudah ada!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                } else {
                    String sql = "INSERT INTO tb_datanilai VALUES('"+kdnilaiTxt.getText()+"', '"+nisTxt.getText()+"', '"+namaTxt.getText()+"', '"+n1Txt.getText()+"', '"+n2Txt.getText()+"', '"+n3Txt.getText()+"', "
                            + "'"+n4Txt.getText()+"', '"+n5Txt.getText()+"', '"+n6Txt.getText()+"', '"+n7Txt.getText()+"', '"+n8Txt.getText()+"', '"+n9Txt.getText()+"', '"+n10Txt.getText()+"', '"+n11Txt.getText()+"', "
                            + "'"+n12Txt.getText()+"', '"+n13Txt.getText()+"', '"+n14Txt.getText()+"', '"+n15Txt.getText()+"', '"+n16Txt.getText()+"', '"+ratarataTxt.getText()+"', '"+kelas+"', '"+semester+"', '"+tahunajaran+"')";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Nilai akademik siswa berhasil disimpan!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException | HeadlessException e){
                JOptionPane.showMessageDialog(null, "Nilai akademik siswa gagal disimpan!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        getNilaiSiswa();
        kd_nilai = 0;
        nisTxt.setText("");
        namaTxt.setText("");
        n1Txt.setText("");
        n2Txt.setText("");
        n3Txt.setText("");
        n4Txt.setText("");
        n5Txt.setText("");
        n6Txt.setText("");
        n7Txt.setText("");
        n8Txt.setText("");
        n9Txt.setText("");
        n10Txt.setText("");
        n11Txt.setText("");
        n12Txt.setText("");
        n13Txt.setText("");
        n14Txt.setText("");
        n15Txt.setText("");
        n16Txt.setText("");
        ratarataTxt.setText("");
        kelasCmb.setSelectedIndex(0);
        semesterCmb.setSelectedIndex(0);
        tahunajaranCmb.setSelectedIndex(0);
        tahunajaranTxt.setText("");
        kdnilaiTxt.setText("");
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void kelasCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasCmbActionPerformed
        // TODO add your handling code here:
        if (kelasCmb.getSelectedIndex()==0){
            kelas="";}
        else if(kelasCmb.getSelectedIndex()==1){
            kelas="VII-A";}
        else if(kelasCmb.getSelectedIndex()==2){
            kelas="VII-B";}
        else if(kelasCmb.getSelectedIndex()==3){
            kelas="VIII-A";}
        else if(kelasCmb.getSelectedIndex()==4){
            kelas="VIII-B";}
        else if(kelasCmb.getSelectedIndex()==5){
            kelas="IX-A";}
        else if(kelasCmb.getSelectedIndex()==6){
            kelas="IX-B";}
    }//GEN-LAST:event_kelasCmbActionPerformed

    private void tahunajaranCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunajaranCmbActionPerformed
        // TODO add your handling code here:\
        if (tahunajaranCmb.getSelectedIndex()==0){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==1){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==2){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==3){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==4){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==5){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==6){
            tahunajaranTxt.setEnabled(false);
            tahunajaranTxt.setText("");}
        else if(tahunajaranCmb.getSelectedIndex()==7){
            tahunajaranTxt.setEnabled(true);}
    }//GEN-LAST:event_tahunajaranCmbActionPerformed

    private void n1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1TxtActionPerformed

    private void cari1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari1BtnActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datasiswa WHERE Nis_Siswa like '%"+cari1Txt.getText()+"%' or Nama like '%"+cari1Txt.getText()+"%'");
            datasiswaTbl.setModel(DbUtils.resultSetToTableModel(sql));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cari1BtnActionPerformed

    private void refresh1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1BtnActionPerformed
        // TODO add your handling code here:
        getDataSiswa();
        cari1Txt.setText("");
    }//GEN-LAST:event_refresh1BtnActionPerformed

    private void datasiswaTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datasiswaTblMouseClicked
        // TODO add your handling code here:
        try {
            int row = datasiswaTbl.getSelectedRow();
            String kliktabel=(datasiswaTbl.getModel().getValueAt(row,0).toString());
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT Nis_Siswa, Nama FROM tb_datasiswa WHERE Nis_siswa='"+kliktabel+"'");

            if (sql.next()) {
                nis = sql.getInt("Nis_siswa");
                String nisString = Integer.toString(nis);
                nisTxt.setText(nisString);
                String nama = sql.getString("Nama");
                namaTxt.setText(nama);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_datasiswaTblMouseClicked

    private void semesterCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterCmbActionPerformed
        // TODO add your handling code here:
        if (semesterCmb.getSelectedIndex()==0){
            semester="";}
        else if(semesterCmb.getSelectedIndex()==1){
            semester="Ganjil";}
        else if(semesterCmb.getSelectedIndex()==2){
            semester="Genap";}
    }//GEN-LAST:event_semesterCmbActionPerformed

    private void datanilaiTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datanilaiTblMouseClicked
        // TODO add your handling code here:
        try {
            int row = datanilaiTbl.getSelectedRow();
            String kliktabel=(datanilaiTbl.getModel().getValueAt(row,0).toString());
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_datanilai WHERE Kd_Nilai='"+kliktabel+"'");

            if (sql.next()) {
                kd_nilai = sql.getInt("Kd_Nilai");
                String kdnilaiString = Integer.toString(kd_nilai);
                kdnilaiTxt.setText(kdnilaiString);
                nis = sql.getInt("Nis_Siswa");
                String nisString = Integer.toString(nis);
                nisTxt.setText(nisString);
                String nama = sql.getString("Nama");
                namaTxt.setText(nama);
                double nilai1 = sql.getDouble("Qurdis");
                String qurdis = Double.toString(nilai1);
                n1Txt.setText(qurdis);
                double nilai2 = sql.getDouble("Aqidah");
                String aqidah = Double.toString(nilai2);
                n2Txt.setText(aqidah);
                double nilai3 = sql.getDouble("Fiqih");
                String fiqih = Double.toString(nilai3);
                n3Txt.setText(fiqih);
                double nilai4 = sql.getDouble("SKI");
                String ski = Double.toString(nilai4);
                n4Txt.setText(ski);
                double nilai5 = sql.getDouble("PKN");
                String pkn = Double.toString(nilai5);
                n5Txt.setText(pkn);
                double nilai6 = sql.getDouble("B_Indonesia");
                String b_indo = Double.toString(nilai6);
                n6Txt.setText(b_indo);
                double nilai7 = sql.getDouble("B_Arab");
                String b_arab = Double.toString(nilai7);
                n7Txt.setText(b_arab);
                double nilai8 = sql.getDouble("B_Inggris");
                String b_ing = Double.toString(nilai8);
                n8Txt.setText(b_ing);
                double nilai9 = sql.getDouble("MTK");
                String mtk = Double.toString(nilai9);
                n9Txt.setText(mtk);
                double nilai10 = sql.getDouble("IPA");
                String ipa = Double.toString(nilai10);
                n10Txt.setText(ipa);
                double nilai11 = sql.getDouble("IPS");
                String ips = Double.toString(nilai11);
                n11Txt.setText(ips);
                double nilai12 = sql.getDouble("Seni_Budaya");
                String senbud = Double.toString(nilai12);
                n12Txt.setText(senbud);
                double nilai13 = sql.getDouble("Penjas");
                String penjas = Double.toString(nilai13);
                n13Txt.setText(penjas);
                double nilai14 = sql.getDouble("TIK");
                String tik = Double.toString(nilai14);
                n14Txt.setText(tik);
                double nilai15 = sql.getDouble("BTQ");
                String btq = Double.toString(nilai15);
                n15Txt.setText(btq);
                double nilai16 = sql.getDouble("Prakarya");
                String prakarya = Double.toString(nilai16);
                n16Txt.setText(prakarya);
                double nilairata = sql.getDouble("Nilai_Ratarata");
                String n_rata2 = Double.toString(nilairata);
                ratarataTxt.setText(n_rata2);

                String kls = sql.getString("Kelas");
                if(kls.equals("")){
                    kelasCmb.setSelectedIndex(0);}
                else if(kls.equals("VII-A")){
                    kelasCmb.setSelectedIndex(1);}
                else if(kls.equals("VII-B")){
                    kelasCmb.setSelectedIndex(2);}
                else if(kls.equals("VIII-A")){
                    kelasCmb.setSelectedIndex(3);}
                else if(kls.equals("VIII-B")){
                    kelasCmb.setSelectedIndex(4);}
                else if(kls.equals("IX-A")){
                    kelasCmb.setSelectedIndex(5);}
                else if(kls.equals("IX-B")){
                    kelasCmb.setSelectedIndex(6);}

                String smstr = sql.getString("Semester");
                if(smstr.equals("")){
                    semesterCmb.setSelectedIndex(0);}
                else if(smstr.equals("Ganjil")){
                    semesterCmb.setSelectedIndex(1);}
                else if(smstr.equals("Genap")){
                    semesterCmb.setSelectedIndex(2);}

                String thnajaran = sql.getString("Tahun_Ajaran");
                if(thnajaran.equals("")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(0);}
                else if(thnajaran.equals("2018/2019")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(1);}
                else if(thnajaran.equals("2019/2020")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(2);}
                else if(thnajaran.equals("2020/2021")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(3);}
                else if(thnajaran.equals("2021/2022")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(4);}
                else if(thnajaran.equals("2022/2023")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(5);}
                else if(thnajaran.equals("2023/2024")){
                    tahunajaranTxt.setEnabled(false);
                    tahunajaranTxt.setText("");
                    tahunajaranCmb.setSelectedIndex(6);}
                else{
                    tahunajaranTxt.setEnabled(true);
                    tahunajaranTxt.setText(thnajaran);
                    tahunajaranCmb.setSelectedIndex(7);
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
        kdnilaiTxt.setEnabled(false);
    }//GEN-LAST:event_datanilaiTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Nilai_Siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bersihkanBtn;
    private javax.swing.JButton cari1Btn;
    private javax.swing.JTextField cari1Txt;
    private javax.swing.JButton cari2Btn;
    private javax.swing.JTextField cari2Txt;
    private javax.swing.JTable datanilaiTbl;
    private javax.swing.JTable datasiswaTbl;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JButton infoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> kategoriCmb;
    private javax.swing.JTextField kdnilaiTxt;
    private javax.swing.JComboBox<String> kelasCmb;
    private javax.swing.JTextField n10Txt;
    private javax.swing.JTextField n11Txt;
    private javax.swing.JTextField n12Txt;
    private javax.swing.JTextField n13Txt;
    private javax.swing.JTextField n14Txt;
    private javax.swing.JTextField n15Txt;
    private javax.swing.JTextField n16Txt;
    private javax.swing.JTextField n1Txt;
    private javax.swing.JTextField n2Txt;
    private javax.swing.JTextField n3Txt;
    private javax.swing.JTextField n4Txt;
    private javax.swing.JTextField n5Txt;
    private javax.swing.JTextField n6Txt;
    private javax.swing.JTextField n7Txt;
    private javax.swing.JTextField n8Txt;
    private javax.swing.JTextField n9Txt;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTextField nisTxt;
    private javax.swing.JButton prosesBtn;
    private javax.swing.JTextField ratarataTxt;
    private javax.swing.JButton refresh1Btn;
    private javax.swing.JButton refresh2Btn;
    private javax.swing.JComboBox<String> semesterCmb;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JComboBox<String> tahunajaranCmb;
    private javax.swing.JTextField tahunajaranTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
