/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_spk_saw;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;



//import net.proteanit.sql.DbUtils;



/**
 *
 * @author Ferdy
 */
public class Form_Proses_Kriteria extends javax.swing.JFrame {
    private Form_Ubah_Bobot formubahbobot = new Form_Ubah_Bobot();
    Koneksi konek = new Koneksi();
    String kelas = "";
    String semester = "";
    String tahunajaran = "";
    DefaultTableModel tmodel1, tmodel2, tmodel3;
    private WindowAdapter windowAdapter = null;
    
    public void initFrame(){
        this.windowAdapter = new WindowAdapter(){
            public void windowClosing(WindowEvent e){
                super.windowClosing(e);
                formubahbobot.dispose();
            }
            public void windowClosed (WindowEvent e){
                super.windowClosed(e);
                formubahbobot.dispose();
            }
            
        };
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.addWindowListener(this.windowAdapter);
    }
    
    private void tampilkan(){
        if(kelas.equals("") || semester.equals("") || tahunajaran.equals("")){
            tampilkanBtn.setEnabled(false);
        } else {
            tampilkanBtn.setEnabled(true);
        }
    }
    
    
    
    public void tabelmodelnormalisasi(){
       tmodel3 =new DefaultTableModel();
       tmodel3.addColumn("Nis");
       tmodel3.addColumn("Nama");
       tmodel3.addColumn("Nilai Pd");
       tmodel3.addColumn("Nilai Sikap");
       tmodel3.addColumn("Nilai Ekskul");
       tmodel3.addColumn("Absensi");
       tmodel3.addColumn("Nilai Akademik");
       normalisasiTbl.setModel(tmodel3);
       }
    
    public void alur(){
        tmodel2 = (DefaultTableModel)perankinganTbl.getModel();
        tmodel1 = (DefaultTableModel)kriteriaTbl.getModel();
        if (tmodel1.getRowCount()>0 && tmodel2.getRowCount()>0){
            RankingBtn.setEnabled(true);
            cetakBtn.setEnabled(true);
        } else if (tmodel1.getRowCount()>0 && tmodel2.getRowCount()==0) {
            RankingBtn.setEnabled(true);
            cetakBtn.setEnabled(false);
        } else if (tmodel1.getRowCount()==0 && tmodel2.getRowCount()>0) {
            RankingBtn.setEnabled(false);
            cetakBtn.setEnabled(true);
        } else if (tmodel1.getRowCount()==0 && tmodel2.getRowCount()==0){
            RankingBtn.setEnabled(false);
            cetakBtn.setEnabled(false);
        }
    }
    
    public void alurnormalisasi(){
        tmodel1 = (DefaultTableModel)kriteriaTbl.getModel();
        if(tmodel1.getRowCount()==0){
            normalisasiBtn.setEnabled(false);
        } else {
            normalisasiBtn.setEnabled(true);
        }
    }
    


    /**
     * Creates new form Form_Proses_Kriteria
     */
    public Form_Proses_Kriteria() {
        initComponents();
        initFrame();
        alurnormalisasi();
        this.setLocationRelativeTo(null);
        tmodel3 = (DefaultTableModel)normalisasiTbl.getModel();
        tmodel2 = (DefaultTableModel)perankinganTbl.getModel();
        tmodel1 = (DefaultTableModel)kriteriaTbl.getModel();
        tmodel1.setRowCount(0);
        tmodel2.setRowCount(0);
        tmodel3.setRowCount(0);
        alur();
        tampilkan();
        tahunajaranTxt.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kelasCmb = new javax.swing.JComboBox<>();
        semesterCmb = new javax.swing.JComboBox<>();
        tahunajaranCmb = new javax.swing.JComboBox<>();
        tahunajaranTxt = new javax.swing.JTextField();
        tampilkanBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        kriteriaTbl = new javax.swing.JTable();
        RankingBtn = new javax.swing.JButton();
        ubahbobotBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        perankinganTbl = new javax.swing.JTable();
        clearBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        normalisasiTbl = new javax.swing.JTable();
        normalisasiBtn = new javax.swing.JButton();
        cetakBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Laporan Ranking Siswa");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/computer.png")).getImage());
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        kelasCmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kelasCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Kelas-", "VII-A", "VII-B", "VIII-A", "VIII-B", "IX-A", "IX-B" }));
        kelasCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasCmbActionPerformed(evt);
            }
        });

        semesterCmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        semesterCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Semester-", "Ganjil", "Genap" }));
        semesterCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterCmbActionPerformed(evt);
            }
        });

        tahunajaranCmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tahunajaranCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Tahun Ajaran-", "2018/2019", "2019/2020", "2020/2021", "2021/2022", "2022/2023", "2023/2024", "Input Manual" }));
        tahunajaranCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunajaranCmbActionPerformed(evt);
            }
        });

        tahunajaranTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tahunajaranTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tahunajaranTxtKeyTyped(evt);
            }
        });

        tampilkanBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tampilkanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Show.png"))); // NOI18N
        tampilkanBtn.setText("Tampilkan");
        tampilkanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkanBtnActionPerformed(evt);
            }
        });

        kriteriaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kd Kriteria", "NIS", "Nama", "Nilai Pd", "Nilai Sikap", "Nilai Ekskul", "Absensi", "Akademik", "Kelas", "Semester", "Tahun Ajaran"
            }
        ));
        jScrollPane3.setViewportView(kriteriaTbl);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kelasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(semesterCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tahunajaranCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tahunajaranTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tampilkanBtn)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semesterCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahunajaranCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahunajaranTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tampilkanBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1))
        );

        RankingBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RankingBtn.setText("Tentukan Peringkat");
        RankingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RankingBtnActionPerformed(evt);
            }
        });

        ubahbobotBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ubahbobotBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit.png"))); // NOI18N
        ubahbobotBtn.setText("Edit Bobot");
        ubahbobotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahbobotBtnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Rangking"));

        perankinganTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Total Nilai", "Kelas", "Semester", "Tahun Ajaran"
            }
        ));
        jScrollPane5.setViewportView(perankinganTbl);
        perankinganTbl.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
        );

        clearBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Clear.png"))); // NOI18N
        clearBtn.setText("Clear All");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Normalisasi"));

        normalisasiTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nis", "Nama", "Nilai Pd", "Nilai Sikap", "Nilai Ekskul", "Absensi", "Akademik"
            }
        ));
        jScrollPane7.setViewportView(normalisasiTbl);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
        );

        jScrollPane6.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        normalisasiBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        normalisasiBtn.setText("Normalisasi");
        normalisasiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalisasiBtnActionPerformed(evt);
            }
        });

        cetakBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cetakBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print.png"))); // NOI18N
        cetakBtn.setText("Cetak");
        cetakBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ubahbobotBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(normalisasiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RankingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cetakBtn)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(cetakBtn)
                .addGap(18, 18, 18)
                .addComponent(ubahbobotBtn)
                .addGap(18, 18, 18)
                .addComponent(normalisasiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RankingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(clearBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kelasCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasCmbActionPerformed
        // TODO add your handling code here:
        if (kelasCmb.getSelectedIndex()==0){ 
        kelas="";}
        else if(kelasCmb.getSelectedIndex()==1){
        kelas="VII-A";}
        else if(kelasCmb.getSelectedIndex()==2){
        kelas="VII-B";}
        else if(kelasCmb.getSelectedIndex()==3){
        kelas="VIII-A";}
        else if(kelasCmb.getSelectedIndex()==4){
        kelas="VIII-B";}
        else if(kelasCmb.getSelectedIndex()==5){
        kelas="IX-A";}
        else if(kelasCmb.getSelectedIndex()==6){
        kelas="IX-B";}
    }//GEN-LAST:event_kelasCmbActionPerformed

    private void semesterCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterCmbActionPerformed
        // TODO add your handling code here:
        if (semesterCmb.getSelectedIndex()==0){ 
        semester="";}
        else if(semesterCmb.getSelectedIndex()==1){
        semester="Ganjil";}
        else if(semesterCmb.getSelectedIndex()==2){
        semester="Genap";}
        tampilkan();
    }//GEN-LAST:event_semesterCmbActionPerformed

    private void tahunajaranCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunajaranCmbActionPerformed
        // TODO add your handling code here:
        if (tahunajaranCmb.getSelectedIndex()==0){ 
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");
        tahunajaran="";}
        else if(tahunajaranCmb.getSelectedIndex()==1){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");
        tahunajaran="2018/2019";}
        else if(tahunajaranCmb.getSelectedIndex()==2){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");
        tahunajaran="2019/2020";}
        else if(tahunajaranCmb.getSelectedIndex()==3){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");
        tahunajaran="2020/2021";}
        else if(tahunajaranCmb.getSelectedIndex()==4){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");
        tahunajaran="2021/2022";}
        else if(tahunajaranCmb.getSelectedIndex()==5){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");
        tahunajaran="2022/2023";}
        else if(tahunajaranCmb.getSelectedIndex()==6){
        tahunajaranTxt.setEnabled(false);
        tahunajaranTxt.setText("");
        tahunajaran="2023/2024";}
        else if(tahunajaranCmb.getSelectedIndex()==7){
        tahunajaranTxt.setEnabled(true);
        tahunajaran=tahunajaranTxt.getText();}
        tampilkan();
    }//GEN-LAST:event_tahunajaranCmbActionPerformed

    private void tampilkanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkanBtnActionPerformed
        // TODO add your handling code here:
        if(tahunajaranCmb.getSelectedIndex()==15){
        tahunajaran=tahunajaranTxt.getText();}
        try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT nk.kd_kriteria, nk.nis_siswa, nk.nama, "
                    + "npd.Ratarata_Pd, ns.Ratarata_Sikap, ne.Ratarata_Ekskul, nk.absensi, dn.Nilai_Ratarata, "
                    + "nk.kelas, nk.semester, nk.tahun_ajaran from (tb_nilaikriteria nk left JOIN tb_nilaipd npd on "
                    + "nk.kd_nilaipd = npd.kd_nilaipd) LEFT JOIN tb_nilaisikap ns on nk.kd_nilaisikap = ns.kd_nilaisikap "
                    + "LEFT JOIN tb_nilaiekskul ne on nk.kd_nilaiekskul = ne.kd_nilaiekskul LEFT JOIN tb_datanilai dn on nk.kd_nilai = "
                    + "dn.kd_nilai WHERE nk.kelas='"+kelas+"' AND nk.semester='"+semester+"' AND nk.tahun_ajaran='"+tahunajaran+"';");
            kriteriaTbl.setModel(DbUtils.resultSetToTableModel(sql));
            alur();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_tampilkanBtnActionPerformed

    private void tahunajaranTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tahunajaranTxtKeyTyped
        // TODO add your handling code here:
        String isi = tahunajaranTxt.getText();
        if (isi.length()>0){
            if (kelas.equals("") || semester.equals("")) {
                tampilkanBtn.setEnabled(false);
            } else {
                tampilkanBtn.setEnabled(true);
            }
        } else {
            tampilkanBtn.setEnabled(false);
        }
    }//GEN-LAST:event_tahunajaranTxtKeyTyped

    private void ubahbobotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahbobotBtnActionPerformed
        // TODO add your handling code here:
        formubahbobot.getDataBobot();
        formubahbobot.setVisible(true);
    }//GEN-LAST:event_ubahbobotBtnActionPerformed

    private void RankingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RankingBtnActionPerformed
        // TODO add your handling code here:
        cariperingkat();
        
    }//GEN-LAST:event_RankingBtnActionPerformed

    private void cetakBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakBtnActionPerformed
        new cetaklaporan("./src/ta_spk_saw/Laporan_Ranking_Siswa.jasper");
    }//GEN-LAST:event_cetakBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
         try {
            java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
            String sqlr = "TRUNCATE table tb_peringkat";
            java.sql.PreparedStatement pstr = conn.prepareStatement(sqlr);
            pstr.execute();
            kelasCmb.setSelectedIndex(0);
            semesterCmb.setSelectedIndex(0);
            tahunajaranCmb.setSelectedIndex(0);
            tahunajaranTxt.setText("");
            tampilkanBtn.setEnabled(false);
            tmodel1.setRowCount(0);
            tmodel2.setRowCount(0);
            tmodel3.setRowCount(0);
            alur();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Pembersihan error. Tidak dapat terhubung ke database!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_clearBtnActionPerformed

    private void normalisasiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalisasiBtnActionPerformed
        // TODO add your handling code here:
        normalisasi();
    }//GEN-LAST:event_normalisasiBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Proses_Kriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Proses_Kriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Proses_Kriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Proses_Kriteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Proses_Kriteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RankingBtn;
    private javax.swing.JButton cetakBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JComboBox<String> kelasCmb;
    private javax.swing.JTable kriteriaTbl;
    private javax.swing.JButton normalisasiBtn;
    private javax.swing.JTable normalisasiTbl;
    private javax.swing.JTable perankinganTbl;
    private javax.swing.JComboBox<String> semesterCmb;
    private javax.swing.JComboBox<String> tahunajaranCmb;
    private javax.swing.JTextField tahunajaranTxt;
    private javax.swing.JButton tampilkanBtn;
    private javax.swing.JButton ubahbobotBtn;
    // End of variables declaration//GEN-END:variables
public  void normalisasi(){
LinkedList max=new LinkedList();
       LinkedList mm=new LinkedList();
   try {
           
        java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet sql = stm.executeQuery("SELECT MAX(Nilai_Pd), MAX(Nilai_Sikap), MAX(Nilai_Ekskul), MIN(Absensi), MAX(Akademik) FROM tb_altkriteria WHERE Kelas='"+kelas+"' AND Semester='"+semester+"' AND Tahun_Ajaran='"+tahunajaran+"'");
        while (sql.next()){
                    max.add(sql.getString(1));
                    max.add(sql.getString(2));
                    max.add(sql.getString(3));
                    max.add(sql.getString(4));
                    max.add(sql.getString(5));
                } 
        java.sql.Statement snk = conn.createStatement();
        java.sql.ResultSet sqll = stm.executeQuery("SELECT * FROM tb_altkriteria WHERE Kelas='"+kelas+"' AND Semester='"+semester+"' AND Tahun_Ajaran='"+tahunajaran+"'");
        tabelmodelnormalisasi();
        while (sqll.next()){
                          tmodel3.addRow(new Object[]{sqll.getString(2),
                            sqll.getString(3)
                          ,(sqll.getFloat(4)/Float.valueOf(max.get(0).toString())),
                          (sqll.getFloat(5)/Float.valueOf(max.get(1).toString()))
                          ,(sqll.getFloat(6)/Float.valueOf(max.get(2).toString()))
                          ,(Float.valueOf(max.get(3).toString())/sqll.getFloat(7))
                          ,(sqll.getFloat(8)/Float.valueOf(max.get(4).toString()))});
                          
        }  
      
           } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, ex);
        } 
}

public void cariperingkat(){
        try {
            
       LinkedList mm=new LinkedList();
       java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
       java.sql.Statement stm = conn.createStatement();
       java.sql.ResultSet res3 = stm.executeQuery("select * from tb_bobotkriteria");
               while (res3.next()){
                           mm.add(res3.getString(1));
                           mm.add(res3.getString(2));
                           mm.add(res3.getString(3));
                           mm.add(res3.getString(4));
                           mm.add(res3.getString(5));
               }
            for (int t = 0; t < tmodel3.getRowCount(); t++) {
              
                    String sql = "DELETE FROM tb_peringkat WHERE Nis_Siswa";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
            }
            
            int rank = 0;
            for (int x = 0; x < tmodel3.getRowCount(); x++) {
                double r1;
                double r2;
                double r3;
                double r4;
                double r5;
                double w;
                rank++;
                r1=(Float.valueOf(tmodel3.getValueAt(x, 2).toString())*Float.valueOf(mm.get(0).toString()));
                r2=(Float.valueOf(tmodel3.getValueAt(x, 3).toString())*Float.valueOf(mm.get(1).toString()));
                r3=(Float.valueOf(tmodel3.getValueAt(x, 4).toString())*Float.valueOf(mm.get(2).toString()));
                r4=(Float.valueOf(tmodel3.getValueAt(x, 5).toString())*Float.valueOf(mm.get(3).toString()));
                r5=(Float.valueOf(tmodel3.getValueAt(x, 6).toString())*Float.valueOf(mm.get(4).toString()));
                w=r1+r2+r3+r4+r5;
                String sqll = "insert into tb_peringkat  values('"+tmodel3.getValueAt(x, 0).toString()+"',"
                        + "'"+tmodel3.getValueAt(x, 1).toString()+"','"+w+"', '"+kelas+"',"
                        + "'"+semester+"','"+tahunajaran+"')";
                java.sql.PreparedStatement psw = conn.prepareStatement(sqll);
                psw.execute();
            }
            java.sql.Statement stp = conn.createStatement();
            java.sql.ResultSet sqp = stp.executeQuery("SELECT Nis_siswa, Nama, ROUND(Nilai_Ranking,3) AS Nilai_Rangking, Kelas, Semester, Tahun_Ajaran FROM tb_peringkat ORDER BY Nilai_Ranking DESC");
            perankinganTbl.setModel(DbUtils.resultSetToTableModel(sqp));
            alur();
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, ex);
        }
       }
}
