/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_spk_saw;

import javax.swing.JOptionPane;

/**
 *
 * @author Ferdy
 */
public class Form_Login extends javax.swing.JFrame {
    private Tampilan_Utama tampilanutama;
    /**
     * Creates new form Form_Login
     */
    public Form_Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        batalBtn = new javax.swing.JButton();
        passTxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Login");
        setBackground(new java.awt.Color(0, 255, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/computer.png")).getImage());
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(445, 299));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN LOGIN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 170, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Username");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, 30));

        userTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 260, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Password");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 30));

        loginBtn.setBackground(new java.awt.Color(102, 255, 204));
        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(0, 255, 0));
        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 100, -1));

        batalBtn.setBackground(new java.awt.Color(255, 255, 255));
        batalBtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        batalBtn.setForeground(new java.awt.Color(255, 0, 0));
        batalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        batalBtn.setText("EXIT");
        batalBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        batalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalBtnActionPerformed(evt);
            }
        });
        getContentPane().add(batalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 80, 20));

        passTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 260, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String usernya = userTxt.getText();
        String passnya = new String (passTxt.getPassword());
        String pass = "";
        String namaadmin = "";
        int kd_admin = 0;
        String status = "";
        if(usernya.equals("") && passnya.equals("")){
            JOptionPane.showMessageDialog(null, "Input username dan password terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
        } else {
            if(usernya.equals("")){
                JOptionPane.showMessageDialog(null, "Input username terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
            } else {
                if(passnya.equals("")){
                    JOptionPane.showMessageDialog(null, "Input password terlebih dahulu!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                } else {
                    try{
                        java.sql.Connection conn = (java.sql.Connection)Koneksi.getConnection();
                        java.sql.Statement stm = conn.createStatement();
                        java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_admin where username='"+usernya+"'");
                        if(sql.next()){
                            kd_admin = sql.getInt("kd_admin");
                            pass = sql.getString("password");
                            namaadmin = sql.getString("nama");
                            status = sql.getString("status");
                            if(passnya.equals(pass)){
                                tampilanutama = new Tampilan_Utama();
                                JOptionPane.showMessageDialog(null, "Login Berhasil!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                                tampilanutama.kd_admin = kd_admin;
                                tampilanutama.editadmin.setEnabled(true);
                                tampilanutama.login.setEnabled(false);
                                tampilanutama.datasiswa.setEnabled(true);
                                tampilanutama.datakriteria.setEnabled(true);
                                tampilanutama.laporansiswa.setEnabled(true);
                                tampilanutama.datanilaisiswa.setEnabled(true);
                                tampilanutama.adLbl.setVisible(true);
                                tampilanutama.adminLbl.setVisible(true);
                                tampilanutama.adminLbl.setText(namaadmin);
                                tampilanutama.logoutBtn.setVisible(true);
                                tampilanutama.setVisible(true);
                                this.dispose();
                            }
                             else {
                            JOptionPane.showMessageDialog(null, "password salah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                            userTxt.setText("");
                            passTxt.setText("");
                        }
                        }
                         else {
                            JOptionPane.showMessageDialog(null, "username atau password salah!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                            userTxt.setText("");
                            passTxt.setText("");
                        }
                    } catch(Exception e){
                        JOptionPane.showMessageDialog(null, "Tidak dapat terhubung ke database. Pastikan Xampp sudah aktif!","Pemberitahuan",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void batalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_batalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
